using Game.Api.CodeGen.Data;
using Game.Core;
using System.Globalization;
using System.Reflection;
using System.Text;

namespace Game.Api.CodeGen.Writers
{
    internal class ApiInterfaceWriter : FileWriter
    {
        private readonly CodeGenOptions _options;

        public string TargetDirectory => _options.TargetDirectory;
        public string NewLine => _options.NewLine;

        public ApiInterfaceWriter(CodeGenOptions options)
        {
            _options = options;
        }

        public void WriteApiInterfaces(IEnumerable<CodeGenTypeDescriptor> descriptors, string autoGeneratedComment)
        {
            // These are TypeScript module paths, so they always use '/' as the separator regardless
            // of the host OS. ResolveFilePath converts them to OS-specific filesystem paths.
            var interfacesFolder = "interfaces";
            var enumPath = "enums.ts";
            var exportPath = "index.ts";

            var interfacesDir = ResolveFilePath(interfacesFolder);
            var interfacesExist = Directory.Exists(interfacesDir);
            var existingFiles = interfacesExist ? Directory.GetFiles(interfacesDir).ToList() : [];
            if (!interfacesExist)
            {
                Directory.CreateDirectory(interfacesDir);
            }

            // Enumerable/dictionary descriptors are containers, not named types: only their leaf type
            // arguments (collected separately by GetAllUsedDescriptors) become files. Excluding them here
            // stops a Dictionary<,>/List<> descriptor — whose NeedsInterface tracks its element/value —
            // from emitting a bogus IDictionary/IList interface and colliding with the real leaf in the
            // DistinctBy identity. Relying on enumeration order to drop the container was always fragile.
            var allDescriptors = descriptors
                .SelectMany(GetAllUsedDescriptors)
                .Where(d => d.NeedsInterface && !d.UnderlyingType.IsEnumerable())
                .DistinctBy(CodeGenTypeFormatter.GetImportText);

            // Materialized once: the grouping is enumerated by the foreach below and again by
            // GetExportsText, and re-running the lazy chain would repeat the reflection-heavy
            // SelectMany(GetAllUsedDescriptors) + DistinctBy walk on each pass.
            var interfaceDataGroups = allDescriptors.Select(d => new InterfaceDescriptorData
            {
                Descriptor = d,
                FilePath = d.IsEnum ? enumPath : $"{interfacesFolder}/{d.LastNamespacePart}.ts"
            })
            .GroupBy(data => data.FilePath)
            .ToList();

            foreach (var group in interfaceDataGroups)
            {
                var fileBuilder = new StringBuilder(autoGeneratedComment);
                var currentExports = group.SelectNotNull(d => CodeGenTypeFormatter.GetImportText(d.Descriptor));
                var importedDescriptors = group
                    .SelectMany(data => data.Descriptor.GetDirectlyReferencedDescriptorsForProperties())
                    .Where(d => d.GenericParameterPosition < 0 && d.NeedsInterface)
                    .ExceptBy(currentExports, CodeGenTypeFormatter.GetImportText);

                if (importedDescriptors.Any())
                {
                    fileBuilder.AppendLine(CodeGenTypeFormatter.GetImportText(importedDescriptors, "../"));
                }

                foreach (var interfaceType in group.OrderBy(d => d.Descriptor.TypeName))
                {
                    if (interfaceType.Descriptor.IsEnum)
                    {
                        WriteEnumToBuilder(interfaceType.Descriptor, fileBuilder);
                    }
                    else
                    {
                        WriteInterfaceToBuilder(interfaceType.Descriptor, fileBuilder);
                    }

                    fileBuilder.AppendLine(Environment.NewLine);
                }

                var groupFilePath = ResolveFilePath(group.Key);
                OverwriteFileIfTextDiffers(groupFilePath, fileBuilder.ToString().TrimEnd().ReplaceLineEndings(NewLine));
                existingFiles.Remove(groupFilePath);
            }

            OverwriteFileIfTextDiffers(ResolveFilePath(exportPath), $"{autoGeneratedComment}{GetExportsText(interfaceDataGroups)}".ReplaceLineEndings(NewLine));

            foreach (var file in existingFiles)
            {
                File.Delete(file);
            }
        }

        private static void WriteEnumToBuilder(CodeGenTypeDescriptor descriptor, StringBuilder builder)
        {
            if (descriptor.IsObsolete)
            {
                builder.AppendLine($"/** @deprecated {descriptor.ObsoleteMessage} */");
            }

            builder.AppendLine($"export enum {CodeGenTypeFormatter.GetTypeText(descriptor)} {{");
            var fields = descriptor.UnderlyingType.GetFields(BindingFlags.Public | BindingFlags.Static);
            foreach (var field in fields)
            {
                // Render from the member name and its declared raw constant value rather than casting
                // to int: that keeps the right name for aliased members and avoids truncating/throwing
                // on a non-int backing type (e.g. byte/long-backed enums) — the same approach
                // ConstantsWriter.RenderValue takes.
                var rawValue = field.GetRawConstantValue() ?? throw new InvalidOperationException($"Failed to get enum value for {descriptor.Name}->{field.Name}");
                var obsoleteAttribute = field.GetCustomAttribute<ObsoleteAttribute>();
                if (obsoleteAttribute is not null)
                {
                    builder.AppendLine($"\t/** @deprecated {obsoleteAttribute.Message} */");
                }

                builder.AppendLine($"\t{field.Name} = {Convert.ToString(rawValue, CultureInfo.InvariantCulture)},");
            }

            builder.Append('}');
        }

        private static void WriteInterfaceToBuilder(CodeGenTypeDescriptor descriptor, StringBuilder builder)
        {
            if (descriptor.IsObsolete)
            {
                builder.AppendLine($"/** @deprecated {descriptor.ObsoleteMessage} */");
            }

            builder.AppendLine($"export interface {CodeGenTypeFormatter.GetInterfaceName(descriptor, true)} {{");
            foreach (var prop in descriptor.PropertyDescriptors)
            {
                if (prop.IsObsolete)
                {
                    builder.AppendLine($"\t/** @deprecated {prop.ObsoleteMessage} */");
                }

                builder.AppendLine($"\t{CodeGenTypeFormatter.GetParameterText(prop, true)};");
            }

            builder.Append('}');
        }

        private static IEnumerable<CodeGenTypeDescriptor> GetAllUsedDescriptors(CodeGenTypeDescriptor type)
        {
            var childTypes = type.PropertyDescriptors
                .Concat(type.GenericArgumentDescriptors);

            return childTypes
                .SelectMany(GetAllUsedDescriptors)
                .Append(type);
        }

        private string ResolveFilePath(string modulePath)
        {
            // Group keys and module paths use '/' as the canonical TypeScript separator; convert to
            // the host OS separator so the resulting filesystem path is valid on Windows and Linux.
            return Path.Combine(TargetDirectory, modulePath.Replace('/', Path.DirectorySeparatorChar));
        }

        private static string GetExportsText(IEnumerable<IGrouping<string, InterfaceDescriptorData>> interfaceDataGroups)
        {
            return string.Join(Environment.NewLine, interfaceDataGroups.OrderBy(g => g.Key).Select(g => $"export * from './{g.Key}';"));
        }
    }
}
