using Game.Api.CodeGen.Data;
using Game.Core;
using System.Text;

namespace Game.Api.CodeGen.Writers
{
    internal class ApiMapWriter : FileWriter
    {
        private readonly CodeGenOptions _options;

        public string TargetDirectory => _options.TargetDirectory;
        public string NewLine => _options.NewLine;

        public ApiMapWriter(CodeGenOptions options)
        {
            _options = options;
        }

        public void WriteApiMap(IEnumerable<EndpointMetadata> endpointData, string autoGeneratedComment)
        {
            var orderedData = endpointData.OrderBy(end => end.Endpoint).ToList();
            var filePath = Path.Combine(TargetDirectory, "api-type-map.ts");
            var strBuilder = new StringBuilder(autoGeneratedComment);
            var allTypes = orderedData
                .SelectMany(e => e.ParameterDescriptors.Append(e.ResponseDescriptor))
                .WhereNotNull()
                .SelectMany(d => d.GetSelfAndGenericArgumentReferences())
                .Where(t => t.NeedsInterface);

            if (allTypes.Any())
            {
                strBuilder.AppendLine(CodeGenTypeFormatter.GetImportText(allTypes));
            }

            strBuilder.AppendLine("export type ApiResponseTypes = {");
            foreach (var endpoint in orderedData)
            {
                strBuilder.AppendLine($"\t'{endpoint.Endpoint}': {CodeGenTypeFormatter.GetTypeText(endpoint.ResponseDescriptor)};");
            }

            strBuilder.AppendLine($"}};{Environment.NewLine}");

            strBuilder.AppendLine("export type ApiRequestTypes = {");
            foreach (var endpoint in orderedData.Where(endp => endp.ParameterDescriptors.Count > 0))
            {
                strBuilder.AppendLine($"\t'{endpoint.Endpoint}': {CodeGenTypeFormatter.GetParametersTypeText(endpoint)};");
            }

            strBuilder.AppendLine($"}};{Environment.NewLine}");
            strBuilder.AppendLine($"export type ApiEndpoint = keyof ApiResponseTypes;{Environment.NewLine}");
            strBuilder.AppendLine("export type ApiEndpointOptionalRequest = {");
            strBuilder.AppendLine("\t[K in keyof ApiRequestTypes]: undefined extends ApiRequestTypes[K] ? K : never;");
            strBuilder.AppendLine($"}}[keyof ApiRequestTypes];{Environment.NewLine}");
            strBuilder.AppendLine($"export type ApiEndpointWithRequest = keyof ApiRequestTypes;{Environment.NewLine}");
            strBuilder.AppendLine($"export type ApiEndpointNoRequest = ApiEndpointOptionalRequest | Exclude<ApiEndpoint, ApiEndpointWithRequest>;{Environment.NewLine}");
            strBuilder.Append("export type ApiResponseType = ApiResponseTypes[ApiEndpoint];");

            Directory.CreateDirectory(TargetDirectory);
            OverwriteFileIfTextDiffers(filePath, strBuilder.ToString().ReplaceLineEndings(NewLine));
        }
    }
}
