using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;

namespace Game.Api.CodeGen.Writers
{
    /// <summary>
    /// Emits the frontend's <c>game-constants.ts</c> from the backend's <c>[ClientMirrored]</c>
    /// constants classes (<see cref="Game.Core.GameConstants"/>), so gameplay constants shared across
    /// the FE/BE boundary — tick size, exp curve, loadout cap, … — have a single source of truth
    /// rather than hand-copied literals on both sides (issue #306). Each public constant becomes an
    /// <c>export const SCREAMING_SNAKE = value;</c>.
    /// </summary>
    internal partial class ConstantsWriter : FileWriter
    {
        // The generated module sits alongside the API types (so it is covered by the CI
        // codegen-drift check) and is consumed directly by the frontend via its deep path, the same
        // way the static attribute-modifier table is.
        private const string FileName = "game-constants.ts";

        private readonly CodeGenOptions _options;

        public ConstantsWriter(CodeGenOptions options)
        {
            _options = options;
        }

        public void WriteConstants(IEnumerable<FieldInfo> constants, string autoGeneratedComment)
        {
            var builder = new StringBuilder(autoGeneratedComment);
            foreach (var constant in constants)
            {
                builder.AppendLine(RenderConstant(constant));
            }

            Directory.CreateDirectory(_options.TargetDirectory);
            var filePath = Path.Combine(_options.TargetDirectory, FileName);
            OverwriteFileIfTextDiffers(filePath, builder.ToString().TrimEnd().ReplaceLineEndings(_options.NewLine));
        }

        internal static string RenderConstant(FieldInfo constant)
        {
            return $"export const {ToScreamingSnakeCase(constant.Name)} = {RenderValue(constant.GetRawConstantValue())};";
        }

        /// <summary>Converts a PascalCase constant name (e.g. <c>MsPerTick</c>) to the TypeScript SCREAMING_SNAKE_CASE convention (e.g. <c>MS_PER_TICK</c>).</summary>
        internal static string ToScreamingSnakeCase(string name)
        {
            return WordBoundaryRegex().Replace(name, "$1_$2").ToUpperInvariant();
        }

        private static string RenderValue(object? value)
        {
            return value switch
            {
                null => throw new InvalidOperationException("A client-mirrored constant must have a value."),
                bool boolean => boolean ? "true" : "false",
                string text => $"'{text}'",
                _ => Convert.ToString(value, CultureInfo.InvariantCulture)
                    ?? throw new InvalidOperationException($"Could not render the value of constant '{value}'."),
            };
        }

        [GeneratedRegex("([a-z0-9])([A-Z])")]
        private static partial Regex WordBoundaryRegex();
    }
}
