using Game.Core;
using Game.Core.Attributes;
using System.Text;

namespace Game.Api.CodeGen.Writers
{
    /// <summary>
    /// Emits the frontend's damage-type taxonomy tables from the backend domain's
    /// <see cref="DamageTypes"/> (spike #1320): the leaf-type → applicable-keys map and the
    /// key → amplification/resistance attribute pairing. Generated rather than hand-mirrored, so a
    /// backend retune of the taxonomy cannot silently desync the two simulators (the CI codegen-drift
    /// check guards the committed output). Iteration order is preserved for float parity.
    /// </summary>
    internal class DamageTypeMapWriter : FileWriter
    {
        // Sits alongside the API types (covered by the CI codegen-drift check) and is consumed by the
        // frontend's $lib/battle/damage-types.ts.
        private const string FileName = "damage-types.ts";

        private readonly CodeGenOptions _options;

        public DamageTypeMapWriter(CodeGenOptions options)
        {
            _options = options;
        }

        public void WriteDamageTypeMaps(string autoGeneratedComment)
        {
            var builder = new StringBuilder(autoGeneratedComment);
            builder.AppendLine("import { EAttribute, EDamageType, EDamageTypeKey } from './enums.ts';");
            builder.AppendLine();

            // Leaf type → the keys whose amp/resist apply to it, in fixed iteration order.
            builder.AppendLine("export const DAMAGE_TYPE_APPLIES = {");
            foreach (var type in DamageTypes.LeafTypes)
            {
                var keys = DamageTypes.Applies(type).Select(k => $"EDamageTypeKey.{EnumName(k)}");
                builder.AppendLine($"\t[EDamageType.{EnumName(type)}]: [{string.Join(", ", keys)}],");
            }

            builder.AppendLine("} as const;");
            builder.AppendLine();

            // Key → the amplification / resistance attribute it backs. An amplification-only weapon key (#1340)
            // emits a null resistance.
            builder.AppendLine("export const DAMAGE_TYPE_KEY_ATTRIBUTES = {");
            foreach (var info in DamageTypes.Keys)
            {
                var resistance = info.Resistance is EAttribute res ? $"EAttribute.{EnumName(res)}" : "null";
                builder.AppendLine(
                    $"\t[EDamageTypeKey.{EnumName(info.Key)}]: {{ amplification: EAttribute.{EnumName(info.Amplification)}, resistance: {resistance} }},");
            }

            builder.AppendLine("} as const;");
            builder.AppendLine();

            // DoT leaf type → its per-second accumulator attribute, in the fixed order the end-of-tick DoT
            // phase folds them (a parity contract — float addition is not associative).
            builder.AppendLine("export const DAMAGE_TYPE_DOT_ACCUMULATORS = [");
            foreach (var info in DamageTypes.DotAccumulators)
            {
                builder.AppendLine(
                    $"\t{{ type: EDamageType.{EnumName(info.Type)}, accumulator: EAttribute.{EnumName(info.Accumulator)} }},");
            }

            builder.Append("] as const;");

            Directory.CreateDirectory(_options.TargetDirectory);
            var filePath = Path.Combine(_options.TargetDirectory, FileName);
            OverwriteFileIfTextDiffers(filePath, builder.ToString().ReplaceLineEndings(_options.NewLine));
        }

        private static string EnumName<TEnum>(TEnum value) where TEnum : struct, Enum
        {
            return Enum.GetName(value)
                ?? throw new InvalidOperationException($"'{value}' is not a named {typeof(TEnum).Name} value.");
        }
    }
}
