using Game.Api.CodeGen.Data;
using Game.Core;
using System.Text;

namespace Game.Api.CodeGen.Writers
{
    internal class SocketMapWriter : FileWriter
    {
        private readonly CodeGenOptions _options;

        public string TargetDirectory => _options.TargetDirectory;
        public string NewLine => _options.NewLine;

        public SocketMapWriter(CodeGenOptions options)
        {
            _options = options;
        }

        public void WriteSocketMap(List<SocketCommandMetadata> commandData, string autoGeneratedComment)
        {
            var orderedData = commandData.OrderBy(c => c.CommandName).ToList();
            var filePath = Path.Combine(TargetDirectory, "api-socket-type-map.ts");
            var strBuilder = new StringBuilder(autoGeneratedComment);
            var allTypes = orderedData
                .SelectNotNull(c => c.ResponseDescriptor)
                .Concat(orderedData.SelectNotNull(c => c.ParameterDescriptor))
                .Where(d => d.NeedsInterface);

            if (allTypes.Any())
            {
                strBuilder.AppendLine(CodeGenTypeFormatter.GetImportText(allTypes));
            }

            strBuilder.AppendLine("export type ApiSocketResponseTypes = {");
            foreach (var command in orderedData)
            {
                strBuilder.AppendLine($"\t'{command.CommandName}': {CodeGenTypeFormatter.GetTypeText(command.ResponseDescriptor)};");
            }

            strBuilder.AppendLine($"}};{Environment.NewLine}");

            strBuilder.AppendLine("export type ApiSocketRequestTypes = {");
            foreach (var command in orderedData.Where(c => c.ParameterDescriptor is not null))
            {
                strBuilder.AppendLine($"\t'{command.CommandName}': {CodeGenTypeFormatter.GetTypeText(command.ParameterDescriptor)};");
            }

            strBuilder.AppendLine($"}};{Environment.NewLine}");
            strBuilder.AppendLine($"export type ApiSocketCommand = keyof ApiSocketResponseTypes;{Environment.NewLine}");
            strBuilder.AppendLine($"export type ApiSocketCommandWithRequest = keyof ApiSocketRequestTypes;{Environment.NewLine}");
            strBuilder.AppendLine($"export type ApiSocketCommandNoRequest = Exclude<ApiSocketCommand, ApiSocketCommandWithRequest>;{Environment.NewLine}");
            strBuilder.Append("export type ApiSocketResponseType = ApiSocketResponseTypes[ApiSocketCommand];");

            Directory.CreateDirectory(TargetDirectory);
            OverwriteFileIfTextDiffers(filePath, strBuilder.ToString().ReplaceLineEndings(NewLine));
        }
    }
}
