using Game.Core;
using Game.Core.Attributes.Modifiers;
using System.Globalization;
using System.Text;

namespace Game.Api.CodeGen.Writers
{
    /// <summary>
    /// Emits the frontend's <c>STATIC_ATTRIBUTE_MODIFIERS</c> table from the backend domain's
    /// <see cref="StaticAttributeModifiers.All"/>. The engine's base/derived attribute formulas are
    /// thereby generated rather than hand-mirrored, so a backend-only retune can no longer silently
    /// desync the two implementations (issue #282).
    /// </summary>
    internal class StaticModifierWriter : FileWriter
    {
        // The generated module sits alongside the API types (so it is covered by the CI
        // codegen-drift check) and is consumed by the frontend's $lib/battle/attribute-modifier.ts.
        private const string FileName = "attribute-modifiers.ts";

        private readonly CodeGenOptions _options;

        public StaticModifierWriter(CodeGenOptions options)
        {
            _options = options;
        }

        public void WriteStaticModifiers(IReadOnlyList<AttributeModifier> modifiers, string autoGeneratedComment)
        {
            var builder = new StringBuilder(autoGeneratedComment);
            builder.AppendLine("import { EAttribute, EAttributeModifierSource, EModifierType } from './enums.ts';");
            builder.AppendLine();
            builder.AppendLine("export const STATIC_ATTRIBUTE_MODIFIERS = [");
            foreach (var modifier in modifiers)
            {
                builder.AppendLine($"\t{RenderModifier(modifier)},");
            }

            builder.Append("] as const;");

            Directory.CreateDirectory(_options.TargetDirectory);
            var filePath = Path.Combine(_options.TargetDirectory, FileName);
            OverwriteFileIfTextDiffers(filePath, builder.ToString().ReplaceLineEndings(_options.NewLine));
        }

        private static string RenderModifier(AttributeModifier modifier)
        {
            var fields = new List<string>
            {
                $"attribute: EAttribute.{EnumName(modifier.Attribute)}",
                $"amount: {modifier.Amount.ToString(CultureInfo.InvariantCulture)}",
                $"type: EModifierType.{EnumName(modifier.Type)}",
                $"source: EAttributeModifierSource.{EnumName(modifier.Source)}",
            };

            // derivedSource is only meaningful for Derived modifiers; omitting it elsewhere keeps the
            // generated table aligned with the frontend's discriminated AttributeModifier union, where
            // a BaseAttributeModifier carries no derivedSource at all.
            if (modifier.Source is EAttributeModifierSource.Derived)
            {
                fields.Add($"derivedSource: EAttribute.{EnumName(modifier.DerivedSource)}");
            }

            return $"{{ {string.Join(", ", fields)} }}";
        }

        private static string EnumName<TEnum>(TEnum value) where TEnum : struct, Enum
        {
            return Enum.GetName(value)
                ?? throw new InvalidOperationException($"'{value}' is not a named {typeof(TEnum).Name} value.");
        }
    }
}
