version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/UI"
    schedule:
      interval: "weekly"
    groups:
      dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@emnapi/core"
      - dependency-name: "@emnapi/runtime"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dotnet-runtime:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
          - "Microsoft.Extensions.*"
          - "Microsoft.AspNetCore.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
