-- Baseline static reference data for the end-to-end (Playwright) stack.
--
-- WHY THIS EXISTS: the dockerized Game.Api applies EF migrations on startup, but those migrations
-- only seed the *intrinsic*, enum-backed reference data (Attributes, Roles, LogTypes, …) via
-- HasData. The *static* reference data (Skills, Enemies, Zones, …) is content authored through the
-- admin tools and is deliberately NOT encoded in the application or its migrations (see
-- docs/backend.md "Reference Data"). A freshly-migrated database therefore has none of it.
--
-- Account creation, however, gives every new player the starter skills 0/1/2
-- (LoginController.CreateAccount), so without at least those Skill rows the very first signup fails
-- with an FK violation (FK_PlayerSkills_Skills_SkillId) and the whole e2e suite cannot log in. This
-- script seeds the minimal, coherent slice of static reference data the suite needs:
--   * Skills 0/1/2          – required by new-player creation
--   * one Zone with enemies – so the Enemies admin catalogue has rows and the fight screen is playable
--
-- It is applied against the e2e Postgres AFTER the API has migrated (the CI workflow runs it once
-- the API answers). Every statement is idempotent (ON CONFLICT DO NOTHING), so re-running is safe.
-- It is intentionally separate from the app: production/local databases are never touched by it.

-- Starter skills (ids 0/1/2 are referenced directly by LoginController.CreateAccount).
INSERT INTO "Skills" ("Id", "Name", "BaseDamage", "Description", "CooldownMs", "IconPath") VALUES
  (0, 'Strike', 10, 'A basic physical attack.', 1000, ''),
  (1, 'Cleave', 8, 'A sweeping blow that favours raw power.', 1500, ''),
  (2, 'Focus', 6, 'Channel energy into a sharper, magical hit.', 1200, '')
ON CONFLICT ("Id") DO NOTHING;

-- How each skill scales (Strength = 0, Intellect = 2 per EAttribute).
INSERT INTO "SkillDamageMultipliers" ("SkillId", "AttributeId", "Multiplier") VALUES
  (0, 0, 1.0),
  (1, 0, 1.0),
  (2, 2, 1.0)
ON CONFLICT ("SkillId", "AttributeId") DO NOTHING;

-- A starter zone for new players (Player.CurrentZoneId defaults to 0).
INSERT INTO "Zones" ("Id", "Name", "Description", "Order", "LevelMin", "LevelMax") VALUES
  (0, 'Verdant Hollow', 'A quiet glade where new heroes cut their teeth.', 0, 1, 10)
ON CONFLICT ("Id") DO NOTHING;

-- A couple of low-level enemies to populate the zone (and the Enemies admin catalogue).
INSERT INTO "Enemies" ("Id", "Name", "IsBoss") VALUES
  (0, 'Forest Slime', false),
  (1, 'Wild Boar', false)
ON CONFLICT ("Id") DO NOTHING;

-- Enemy attribute distributions (Strength = 0, Endurance = 1 per EAttribute).
INSERT INTO "AttributeDistributions" ("EnemyId", "AttributeId", "BaseAmount", "AmountPerLevel") VALUES
  (0, 0, 5, 1.0),
  (0, 1, 5, 1.0),
  (1, 0, 7, 1.5),
  (1, 1, 6, 1.0)
ON CONFLICT ("EnemyId", "AttributeId") DO NOTHING;

-- Give the enemies a skill so battles resolve.
INSERT INTO "EnemySkills" ("EnemyId", "SkillId") VALUES
  (0, 0),
  (1, 0)
ON CONFLICT ("EnemyId", "SkillId") DO NOTHING;

-- Place the enemies in the starter zone (equal spawn weight).
INSERT INTO "ZoneEnemies" ("ZoneId", "EnemyId", "Weight") VALUES
  (0, 0, 1),
  (0, 1, 1)
ON CONFLICT ("ZoneId", "EnemyId") DO NOTHING;

-- The base tables use GENERATED BY DEFAULT identity columns seeded above with explicit ids, which
-- leaves their sequences untouched. Advance each past the highest seeded id so later DB-generated
-- inserts (e.g. creating a record through the admin tools) don't collide with a seeded row.
SELECT setval(pg_get_serial_sequence('"Skills"', 'Id'), (SELECT MAX("Id") FROM "Skills"));
SELECT setval(pg_get_serial_sequence('"Enemies"', 'Id'), (SELECT MAX("Id") FROM "Enemies"));
SELECT setval(pg_get_serial_sequence('"Zones"', 'Id'), (SELECT MAX("Id") FROM "Zones"));
