// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	IAddEditAttributesData,
	IAdminUserSearchResults,
	IApplyModRequest,
	IAttribute,
	IAttributeUpdate,
	IAuthTokens,
	IBattlerAttribute,
	IChallenge,
	IChallengeType,
	IChange,
	IDeviceInfoRequest,
	IEnemy,
	IEquipRequest,
	IItem,
	IItemCategory,
	IItemMod,
	IItemModSlot,
	IItemModType,
	ILoginCredentials,
	ILoginResult,
	IPlayerChallenge,
	IPlayerData,
	IPlayerStatistic,
	IRefreshRequest,
	IRemoveModRequest,
	IRole,
	ISetEnemyAttributeDistributions,
	ISetEnemySkillsData,
	ISetEnemySpawnsData,
	ISetTagsData,
	ISetUserRolesData,
	ISetZoneEnemiesData,
	ISkill,
	IStatisticType,
	ITag,
	ITagCategory,
	IUserActionData,
	IZone,
	IZoneEnemy
} from './';

export type ApiResponseTypes = {
	'AdminTools/AddEditChallenges': undefined;
	'AdminTools/AddEditEnemies': undefined;
	'AdminTools/AddEditItemAttributes': undefined;
	'AdminTools/AddEditItemModAttributes': undefined;
	'AdminTools/AddEditItemMods': undefined;
	'AdminTools/AddEditItemModSlots': undefined;
	'AdminTools/AddEditItems': undefined;
	'AdminTools/AddEditSkills': undefined;
	'AdminTools/AddEditTags': undefined;
	'AdminTools/AddEditZones': undefined;
	'AdminTools/ArchiveUser': undefined;
	'AdminTools/BanUser': undefined;
	'AdminTools/GetRoles': IRole[];
	'AdminTools/GetUsers': IAdminUserSearchResults;
	'AdminTools/SetEnemyAttributeDistributions': undefined;
	'AdminTools/SetEnemySkills': undefined;
	'AdminTools/SetEnemySpawns': undefined;
	'AdminTools/SetSkillMultipliers': undefined;
	'AdminTools/SetTagsForItem': undefined;
	'AdminTools/SetTagsForItemMod': undefined;
	'AdminTools/SetUserRoles': undefined;
	'AdminTools/SetZoneEnemies': undefined;
	'Attributes': IAttribute[];
	'Challenges': IChallenge[];
	'Challenges/ChallengeTypes': IChallengeType[];
	'Challenges/Player': IPlayerChallenge[];
	'Enemies': IEnemy[];
	'ItemCategories': IItemCategory[];
	'ItemMods': IItemMod[];
	'ItemMods/ItemModTypes': IItemModType[];
	'Items': IItem[];
	'Items/SlotsForItem': IItemModSlot[];
	'Login': ILoginResult;
	'Login/CreateAccount': undefined;
	'Login/DeviceInfo': undefined;
	'Login/Logout': undefined;
	'Login/Refresh': IAuthTokens;
	'Login/Status': IPlayerData;
	'Player': IPlayerData;
	'Player/ApplyMod': undefined;
	'Player/EquipItem': undefined;
	'Player/RemoveMod': undefined;
	'Player/UnequipItem': undefined;
	'Player/UpdatePlayerStats': IBattlerAttribute[];
	'Skills': ISkill[];
	'Statistics': IPlayerStatistic[];
	'Statistics/StatisticTypes': IStatisticType[];
	'Tags': ITag[];
	'Tags/TagCategories': ITagCategory[];
	'Tags/TagsForItem': ITag[];
	'Tags/TagsForItemMod': ITag[];
	'Zones': IZone[];
	'Zones/ZoneEnemies': IZoneEnemy[];
};

export type ApiRequestTypes = {
	'AdminTools/AddEditChallenges': IChange<IChallenge>[];
	'AdminTools/AddEditEnemies': IChange<IEnemy>[];
	'AdminTools/AddEditItemAttributes': IAddEditAttributesData;
	'AdminTools/AddEditItemModAttributes': IAddEditAttributesData;
	'AdminTools/AddEditItemMods': IChange<IItemMod>[];
	'AdminTools/AddEditItemModSlots': IChange<IItemModSlot>[];
	'AdminTools/AddEditItems': IChange<IItem>[];
	'AdminTools/AddEditSkills': IChange<ISkill>[];
	'AdminTools/AddEditTags': IChange<ITag>[];
	'AdminTools/AddEditZones': IChange<IZone>[];
	'AdminTools/ArchiveUser': IUserActionData;
	'AdminTools/BanUser': IUserActionData;
	'AdminTools/GetUsers': { search?: string, roleId?: number, archived?: boolean, page?: number, pageSize?: number } | undefined;
	'AdminTools/SetEnemyAttributeDistributions': ISetEnemyAttributeDistributions;
	'AdminTools/SetEnemySkills': ISetEnemySkillsData;
	'AdminTools/SetEnemySpawns': ISetEnemySpawnsData;
	'AdminTools/SetSkillMultipliers': IAddEditAttributesData;
	'AdminTools/SetTagsForItem': ISetTagsData;
	'AdminTools/SetTagsForItemMod': ISetTagsData;
	'AdminTools/SetUserRoles': ISetUserRolesData;
	'AdminTools/SetZoneEnemies': ISetZoneEnemiesData;
	'Enemies': { refreshCache?: boolean } | undefined;
	'ItemMods': { refreshCache?: boolean } | undefined;
	'Items': { refreshCache?: boolean } | undefined;
	'Items/SlotsForItem': { itemId: number, refreshCache?: boolean };
	'Login': ILoginCredentials;
	'Login/CreateAccount': ILoginCredentials;
	'Login/DeviceInfo': IDeviceInfoRequest;
	'Login/Logout': IRefreshRequest;
	'Login/Refresh': IRefreshRequest;
	'Player/ApplyMod': IApplyModRequest;
	'Player/EquipItem': IEquipRequest;
	'Player/RemoveMod': IRemoveModRequest;
	'Player/UnequipItem': IEquipRequest;
	'Player/UpdatePlayerStats': IAttributeUpdate[];
	'Skills': { refreshCache?: boolean } | undefined;
	'Tags/TagsForItem': { itemId: number };
	'Tags/TagsForItemMod': { itemModId: number };
	'Zones': { refreshCache?: boolean } | undefined;
	'Zones/ZoneEnemies': { zoneId: number };
};

export type ApiEndpoint = keyof ApiResponseTypes;

export type ApiEndpointOptionalRequest = {
	[K in keyof ApiRequestTypes]: undefined extends ApiRequestTypes[K] ? K : never;
}[keyof ApiRequestTypes];

export type ApiEndpointWithRequest = keyof ApiRequestTypes;

export type ApiEndpointNoRequest = ApiEndpointOptionalRequest | Exclude<ApiEndpoint, ApiEndpointWithRequest>;

export type ApiResponseType = ApiResponseTypes[ApiEndpoint];