// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	IBattleLostResponse,
	IDefeatEnemyRequest,
	IDefeatEnemyResponse,
	INewEnemyModel,
	INewEnemyRequest,
	ISetItemFavoriteRequest
} from './';

export type ApiSocketResponseTypes = {
	'BattleLost': IBattleLostResponse;
	'DefeatEnemy': IDefeatEnemyResponse;
	'NewEnemy': INewEnemyModel;
	'SetItemFavorite': undefined;
	'SocketReplaced': undefined;
};

export type ApiSocketRequestTypes = {
	'DefeatEnemy': IDefeatEnemyRequest;
	'NewEnemy': INewEnemyRequest;
	'SetItemFavorite': ISetItemFavoriteRequest;
};

export type ApiSocketCommand = keyof ApiSocketResponseTypes;

export type ApiSocketCommandWithRequest = keyof ApiSocketRequestTypes;

export type ApiSocketCommandNoRequest = Exclude<ApiSocketCommand, ApiSocketCommandWithRequest>;

export type ApiSocketResponseType = ApiSocketResponseTypes[ApiSocketCommand];