// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

export enum EAttribute {
	Strength = 0,
	Endurance = 1,
	Intellect = 2,
	Agility = 3,
	Dexterity = 4,
	Luck = 5,
	MaxHealth = 6,
	Defense = 7,
	CooldownRecovery = 8,
	/** @deprecated Drop system has been replaced by challenge-based unlocks. */
	DropBonus = 9,
	CriticalChance = 10,
	CriticalDamage = 11,
	DodgeChance = 12,
	BlockChance = 13,
	BlockReduction = 14,
}

export enum EChangeType {
	Add = 0,
	Edit = 1,
	Delete = 2,
}

export enum EItemCategory {
	Helm = 1,
	Chest = 2,
	Leg = 3,
	Boot = 4,
	Weapon = 5,
	Accessory = 6,
}

export enum ERarity {
	Common = 1,
	Uncommon = 2,
	Rare = 3,
	Epic = 4,
	Legendary = 5,
	Mythic = 6,
}

export enum EItemModType {
	Component = 1,
	Prefix = 2,
	Suffix = 3,
}

export enum EChallengeType {
	KillCount = 1,
	BossDefeat = 2,
	ZoneClear = 3,
	TimeTrial = 4,
	LevelReached = 5,
	DamageDealt = 6,
	BattlesWon = 7,
	SkillsUsed = 8,
}

export enum EStatisticType {
	EnemiesKilled = 1,
	BossesDefeated = 2,
	ZonesCleared = 3,
	TotalDamageDealt = 4,
	HighestSingleAttackDamage = 5,
	TotalDamageTaken = 6,
	TotalDamageHealed = 7,
	EnemiesEncountered = 8,
	BattlesWon = 9,
	BattlesLost = 10,
	PlayerDeaths = 11,
	TotalBattleTimeMs = 12,
	FastestVictoryMs = 13,
	TotalSkillsUsed = 14,
}

export enum EEntityType {
	None = 0,
	Enemy = 1,
	Zone = 2,
	Skill = 3,
}

export enum ELogType {
	Damage = 1,
	Debug = 2,
	Exp = 3,
	LevelUp = 4,
	ItemFound = 5,
	EnemyDefeated = 6,
}