// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { IPlayerData } from '../';

export interface IAuthTokens {
	accessToken: string;
	refreshToken: string;
}

export interface IBrowserInfoRequest {
	deviceFingerprintHash?: string;
	deviceMemory?: number;
	hardwareConcurrency?: number;
}

export interface ILoginResult {
	tokens: IAuthTokens;
	player: IPlayerData;
}

export interface IRefreshRequest {
	refreshToken: string;
}