// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { EChallengeType, EEntityType, EStatisticType } from '../';

export interface IChallenge {
	id: number;
	name: string;
	description: string;
	challengeTypeId: EChallengeType;
	statisticType?: EStatisticType;
	entityType: EEntityType;
	targetEntityId?: number;
	progressGoal: number;
	rewardItemId?: number;
	rewardItemModId?: number;
}

export interface IPlayerChallenge {
	challengeId: number;
	progress: number;
	completed: boolean;
	completedAt?: string;
}