// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

export interface IChallenge {
	id: number;
	name: string;
	description: string;
	challengeTypeId: number;
	targetEntityId?: number;
	targetCount: number;
	rewardItemId?: number;
	rewardItemModId?: number;
}

export interface IPlayerChallenge {
	challengeId: number;
	progress: number;
	completed: boolean;
	completedAt?: string;
}