/* This file was automatically generated by Game.Api.CodeGen.
 * Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.
*/

import type { EChangeType } from "../"

export interface IChange<T> {
	item: T;
	changeType: EChangeType;
};

export interface IAddEditAttributesData {
	id: number;
	changes: IChange<IBattlerAttribute>[];
};