// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	EItemCategory,
	EItemModType,
	ERarity,
	IBattlerAttribute
} from '../';

export interface IItemMod {
	id: number;
	name: string;
	description: string;
	itemModTypeId: EItemModType;
	rarityId: ERarity;
	attributes: IBattlerAttribute[];
	tags: number[];
}

export interface IItemModSlot {
	id: number;
	itemId: number;
	itemModSlotTypeId: EItemModType;
}

export interface IItem {
	id: number;
	name: string;
	description: string;
	itemCategoryId: EItemCategory;
	rarityId: ERarity;
	iconPath: string;
	attributes: IBattlerAttribute[];
	modSlots: IItemModSlot[];
	tags: number[];
}

export interface IItemCategory {
	id: number;
	name: string;
}

export interface IItemModType {
	id: number;
	name: string;
}