// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { EStatisticType } from '../';

export interface IPlayerStatistic {
	statisticTypeId: EStatisticType;
	entityId?: number;
	value: number;
}