// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

export interface IAdminUser {
	id: number;
	username: string;
	lastLogin: string;
	archivedAt?: string;
	bannedAt?: string;
	roles: IRole[];
	players: IPlayerSummary[];
}

export interface IAdminUserSearchResults {
	users: IAdminUser[];
	totalCount: number;
	page: number;
	pageSize: number;
}

export interface IPlayerSummary {
	id: number;
	name: string;
	level: number;
	lastActivity: string;
}

export interface IRole {
	id: number;
	name: string;
}

export interface ISetUserRolesData {
	userId: number;
	roleIds: number[];
}

export interface IUserActionData {
	userId: number;
}