// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { IZoneEnemy } from '../';

export interface ISetZoneEnemiesData {
	zoneId: number;
	zoneEnemies: IZoneEnemy[];
}