// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

export interface ISetZoneEnemiesData {
	zoneId: number;
	zoneEnemies: IZoneEnemy[];
}

export interface IZone {
	id: number;
	name: string;
	description: string;
	order: number;
	levelMin: number;
	levelMax: number;
}

export interface IZoneEnemy {
	enemyId: number;
	weight: number;
}