using Game.Api.CodeGen.Data;
using Game.Api.CodeGen.Writers;
using Game.Api.Sockets.Commands;
using Game.Core;
using Game.Core.Attributes.Modifiers;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Reflection;

namespace Game.Api.CodeGen
{
    public class ApiCodeGenerator
    {
        private readonly ILogger<ApiCodeGenerator> _logger;

        public ApiCodeGenerator(ILogger<ApiCodeGenerator> logger)
        {
            _logger = logger;
        }

        public void GenerateCode(Assembly assembly, CodeGenOptions options)
        {
            var start = Stopwatch.GetTimestamp();
            _logger.LogDebug($"Beginning code generation.");

            var controllerTypes = assembly.GetTypes().Where(type => type.IsAssignableTo(typeof(ControllerBase)));
            var endpointMetadata = controllerTypes.SelectMany(c => new ControllerMetadataExtractor(c).Endpoints).ToList();

            var socketCommandTypes = assembly.GetTypes().Where(type => type.IsAssignableTo(typeof(AbstractSocketCommand)) && !type.IsAbstract);
            var socketMetadata = socketCommandTypes.Select(sc => new SocketCommandMetadata(sc)).ToList();

            _logger.LogDebug("Finished analyzing types. Elapsed time {ElapsedTime}", Stopwatch.GetElapsedTime(start));

            var autoGeneratedComment = GetAutoGeneratedComment();

            var apiMapWriter = new ApiMapWriter(options);
            apiMapWriter.WriteApiMap(endpointMetadata, autoGeneratedComment);

            var socketMapWriter = new SocketMapWriter(options);
            socketMapWriter.WriteSocketMap(socketMetadata, autoGeneratedComment);

            var apiTypeDescriptors = endpointMetadata.SelectMany(e => e.ParameterDescriptors.Append(e.ResponseDescriptor)).WhereNotNull();
            var socketTypeDescriptors = socketMetadata.SelectNotNull(s => s.ParameterDescriptor).Concat(socketMetadata.SelectNotNull(s => s.ResponseDescriptor));

            var apiInterfaceWriter = new ApiInterfaceWriter(options);
            apiInterfaceWriter.WriteApiInterfaces(apiTypeDescriptors.Concat(socketTypeDescriptors).Concat(GetClientMirroredEnumDescriptors()), autoGeneratedComment);

            _logger.LogDebug("Finished generating typescript interfaces. Elapsed time {ElapsedTime}", Stopwatch.GetElapsedTime(start));

            var staticModifierWriter = new StaticModifierWriter(options);
            staticModifierWriter.WriteStaticModifiers(StaticAttributeModifiers.All, autoGeneratedComment);

            _logger.LogDebug("Finished generating static domain data. Elapsed time {ElapsedTime}", Stopwatch.GetElapsedTime(start));
        }

        /// <summary>
        /// Domain enums explicitly opted into client mirroring via <see cref="ClientMirroredAttribute"/>,
        /// emitted into the TypeScript client even though no API/socket DTO references them (so the
        /// reflection walk above never reaches them). Discovered by scanning the <see cref="Game.Core"/>
        /// assembly — where the game's domain enums live — so adding a new mirrored enum is a one-line
        /// attribute at its declaration rather than an edit here. The de-duplication in
        /// <see cref="ApiInterfaceWriter"/> makes marking an enum that the walk already reaches harmless.
        /// </summary>
        internal static IEnumerable<CodeGenTypeDescriptor> GetClientMirroredEnumDescriptors()
        {
            return typeof(ClientMirroredAttribute).Assembly.GetTypes()
                .Where(type => type.IsEnum && type.GetCustomAttribute<ClientMirroredAttribute>() is not null)
                .Select(type => new CodeGenTypeDescriptor(type));
        }

        private static string GetAutoGeneratedComment()
        {
            return $"""
                // This file was automatically generated by Game.Api.CodeGen.
                // Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.


                """;
        }
    }
}
