using Game.Api.CodeGen.Data;
using Game.Api.CodeGen.Writers;
using Game.Api.Sockets.Commands;
using Game.Core;
using Game.Core.Attributes.Modifiers;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Reflection;

namespace Game.Api.CodeGen
{
    public class ApiCodeGenerator
    {
        private readonly ILogger<ApiCodeGenerator> _logger;

        public ApiCodeGenerator(ILogger<ApiCodeGenerator> logger)
        {
            _logger = logger;
        }

        public void GenerateCode(Assembly assembly, CodeGenOptions options)
        {
            var start = Stopwatch.GetTimestamp();
            _logger.LogDebug($"Beginning code generation.");

            var controllerTypes = assembly.GetTypes().Where(type => type.IsAssignableTo(typeof(ControllerBase)));
            var endpointMetadata = controllerTypes.SelectMany(c => new ControllerMetadataExtractor(c).Endpoints).ToList();

            var socketCommandTypes = assembly.GetTypes().Where(type => type.IsAssignableTo(typeof(AbstractSocketCommand)) && !type.IsAbstract);
            var socketMetadata = socketCommandTypes.Select(sc => new SocketCommandMetadata(sc)).ToList();

            _logger.LogDebug("Finished analyzing types. Elapsed time {ElapsedTime}", Stopwatch.GetElapsedTime(start));

            var autoGeneratedComment = GetAutoGeneratedComment();

            var apiMapWriter = new ApiMapWriter(options);
            apiMapWriter.WriteApiMap(endpointMetadata, autoGeneratedComment);

            var socketMapWriter = new SocketMapWriter(options);
            socketMapWriter.WriteSocketMap(socketMetadata, autoGeneratedComment);

            var apiTypeDescriptors = endpointMetadata.SelectMany(e => e.ParameterDescriptors.Append(e.ResponseDescriptor)).WhereNotNull();
            var socketTypeDescriptors = socketMetadata.SelectNotNull(s => s.ParameterDescriptor).Concat(socketMetadata.SelectNotNull(s => s.ResponseDescriptor));

            var apiInterfaceWriter = new ApiInterfaceWriter(options);
            apiInterfaceWriter.WriteApiInterfaces(apiTypeDescriptors.Concat(socketTypeDescriptors).Concat(GetDomainEnumDescriptors()), autoGeneratedComment);

            _logger.LogDebug("Finished generating typescript interfaces. Elapsed time {ElapsedTime}", Stopwatch.GetElapsedTime(start));

            var staticModifierWriter = new StaticModifierWriter(options);
            staticModifierWriter.WriteStaticModifiers(StaticAttributeModifiers.All, autoGeneratedComment);

            _logger.LogDebug("Finished generating static domain data. Elapsed time {ElapsedTime}", Stopwatch.GetElapsedTime(start));
        }

        /// <summary>
        /// Game-domain enums that are emitted into the TypeScript client even though no API/socket DTO
        /// references them (so the reflection walk above never reaches them). They are needed because
        /// the generated <c>STATIC_ATTRIBUTE_MODIFIERS</c> table (see <see cref="StaticModifierWriter"/>)
        /// references them by value. Sourced from the <see cref="AttributeModifier"/> properties so the
        /// link to the data that uses them stays explicit.
        /// </summary>
        private static IEnumerable<CodeGenTypeDescriptor> GetDomainEnumDescriptors()
        {
            yield return EnumDescriptor(nameof(AttributeModifier.Type));    // EModifierType
            yield return EnumDescriptor(nameof(AttributeModifier.Source));  // EAttributeModifierSource
        }

        private static CodeGenTypeDescriptor EnumDescriptor(string propertyName)
        {
            var property = typeof(AttributeModifier).GetProperty(propertyName)
                ?? throw new InvalidOperationException($"Property '{propertyName}' not found on {nameof(AttributeModifier)}.");
            return new CodeGenTypeDescriptor(property);
        }

        private static string GetAutoGeneratedComment()
        {
            return $"""
                // This file was automatically generated by Game.Api.CodeGen.
                // Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.


                """;
        }
    }
}
