// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	EChangeType,
	EContentHealthSeverity,
	EDeadLetterReason,
	IAttributeDistribution,
	IBattlerAttribute,
	IClassStarterEquipment,
	IEnemySpawn,
	ILessonStep,
	IProficiencyLevelModifier,
	IProficiencyLevelReward,
	ISkillDamagePortion,
	ISkillEffect,
	ISkillRecipeCondition,
	IZoneEnemy
} from '../';

export interface IAddEditAttributesData {
	id: number;
	changes: IChange<IBattlerAttribute>[];
}

export interface IChange<T> {
	item: T;
	changeType: EChangeType;
}

export interface IContentHealthFinding {
	severity: EContentHealthSeverity;
	check: string;
	entityKind: string;
	entityId: number;
	message: string;
}

export interface IContentHealthReport {
	errorCount: number;
	warningCount: number;
	findings: IContentHealthFinding[];
}

export interface IDeadLetterEntry {
	index: number;
	eventType?: string;
	playerId?: number;
	reason: EDeadLetterReason;
	rawPayload: string;
}

export interface IDeadLetterInspection {
	totalCount: number;
	entries: IDeadLetterEntry[];
}

export interface IDeadLetterReplayResult {
	replayedCount: number;
	remainingCount: number;
}

export interface IReplayDeadLettersData {
	all: boolean;
	payloads?: string[];
}

export interface ISetClassAttributeDistributionsData {
	classId: number;
	attributeDistributions: IAttributeDistribution[];
}

export interface ISetClassStarterEquipmentData {
	classId: number;
	equipment: IClassStarterEquipment[];
}

export interface ISetClassStarterSkillsData {
	classId: number;
	skillIds: number[];
}

export interface ISetEnemyAttributeDistributions {
	enemyId: number;
	attributeDistributions: IAttributeDistribution[];
}

export interface ISetEnemySkillsData {
	enemyId: number;
	skillIds: number[];
}

export interface ISetEnemySpawnsData {
	enemyId: number;
	spawns: IEnemySpawn[];
}

export interface ISetLessonStepsData {
	id: number;
	steps: ILessonStep[];
}

export interface ISetProficiencyModifiersData {
	id: number;
	modifiers: IProficiencyLevelModifier[];
}

export interface ISetProficiencyPrerequisitesData {
	id: number;
	prerequisiteIds: number[];
}

export interface ISetProficiencyRewardsData {
	id: number;
	rewards: IProficiencyLevelReward[];
}

export interface ISetSkillEffectsData {
	id: number;
	changes: IChange<ISkillEffect>[];
}

export interface ISetSkillPortionsData {
	id: number;
	changes: IChange<ISkillDamagePortion>[];
}

export interface ISetSkillRecipeConditionsData {
	id: number;
	conditions: ISkillRecipeCondition[];
}

export interface ISetSkillRecipeInputsData {
	id: number;
	skillIds: number[];
}

export interface ISetTagsData {
	id: number;
	tagIds: number[];
}

export interface ISetZoneEnemiesData {
	zoneId: number;
	zoneEnemies: IZoneEnemy[];
}