// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	EChangeType,
	IAttributeDistribution,
	IBattlerAttribute,
	IEnemySpawn,
	ISkillEffect,
	IZoneEnemy
} from '../';

export interface IAddEditAttributesData {
	id: number;
	changes: IChange<IBattlerAttribute>[];
}

export interface IChange<T> {
	item: T;
	changeType: EChangeType;
}

export interface ISetEnemyAttributeDistributions {
	enemyId: number;
	attributeDistributions: IAttributeDistribution[];
}

export interface ISetEnemySkillsData {
	enemyId: number;
	skillIds: number[];
}

export interface ISetEnemySpawnsData {
	enemyId: number;
	spawns: IEnemySpawn[];
}

export interface ISetSkillEffectsData {
	id: number;
	changes: IChange<ISkillEffect>[];
}

export interface ISetTagsData {
	id: number;
	tagIds: number[];
}

export interface ISetZoneEnemiesData {
	zoneId: number;
	zoneEnemies: IZoneEnemy[];
}