// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { EAttribute } from '../';

export interface IAttribute {
	id: EAttribute;
	name: string;
	description: string;
}

export interface IAttributeUpdate {
	attributeId: number;
	amount: number;
}