// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { IPlayerData, IPlayerSummary } from '../';

export interface IActiveSessionResult {
	active: boolean;
}

export interface IAuthTokens {
	accessToken: string;
	refreshToken: string;
}

export interface ICreateAccountRequest {
	username: string;
	password: string;
	classId: number;
}

export interface ICreatePlayerRequest {
	name: string;
	classId: number;
}

export interface IDeviceInfoRequest {
	deviceMemory?: number;
	hardwareConcurrency?: number;
}

export interface ILoginResult {
	tokens: IAuthTokens;
	playerSummaries: IPlayerSummary[];
}

export interface IRefreshRequest {
	refreshToken: string;
}

export interface ISelectPlayerRequest {
	playerId: number;
	refreshToken: string;
}

export interface ISelectPlayerResult {
	tokens: IAuthTokens;
	player: IPlayerData;
}