// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	EAttribute,
	EChallengeType,
	EEntityType,
	EEquipmentSlot,
	EItemCategory,
	EItemModType,
	EModifierType,
	ERarity,
	ESkillAcquisition,
	ESkillEffectTarget,
	EStatisticType
} from '../';

export interface IAttributeDistribution {
	attributeId: EAttribute;
	baseAmount: number;
	amountPerLevel: number;
}

export interface IAttributeMultiplier {
	attributeId: EAttribute;
	multiplier: number;
}

export interface IBattlerAttribute {
	attributeId: EAttribute;
	amount: number;
}

export interface IChallenge {
	id: number;
	name: string;
	description: string;
	challengeTypeId: EChallengeType;
	statisticType?: EStatisticType;
	entityType: EEntityType;
	targetEntityId?: number;
	progressGoal: number;
	rewardItemId?: number;
	rewardItemModId?: number;
	retiredAt?: string;
}

export interface IClass {
	id: number;
	name: string;
	description: string;
	word: string;
	passiveAttributeId: EAttribute;
	passiveAmount: number;
	passiveScalingAttributeId?: EAttribute;
	passiveScalingAmount: number;
	passiveModifierType: EModifierType;
	starterSkillIds: number[];
	starterEquipment: IClassStarterEquipment[];
	attributeDistributions: IAttributeDistribution[];
	retiredAt?: string;
}

export interface IClassStarterEquipment {
	itemId: number;
	equipmentSlot: EEquipmentSlot;
}

export interface ICreatableClass {
	id: number;
	name: string;
	description: string;
	word: string;
	passiveAttributeId: EAttribute;
	passiveAmount: number;
	passiveScalingAttributeId?: EAttribute;
	passiveScalingAmount: number;
	passiveModifierType: EModifierType;
	attributeDistributions: IAttributeDistribution[];
	starterSkills: ICreatableClassSkill[];
	starterEquipment: ICreatableClassEquipment[];
}

export interface ICreatableClassEquipment {
	itemId: number;
	equipmentSlot: EEquipmentSlot;
	name: string;
}

export interface ICreatableClassSkill {
	id: number;
	name: string;
}

export interface IEnemy {
	id: number;
	name: string;
	isBoss: boolean;
	attributeDistribution: IAttributeDistribution[];
	skillPool: number[];
	spawns: IEnemySpawn[];
	retiredAt?: string;
}

export interface IEnemySpawn {
	zoneId: number;
	weight: number;
}

export interface IItem {
	id: number;
	name: string;
	description: string;
	itemCategoryId: EItemCategory;
	rarityId: ERarity;
	iconPath: string;
	attributes: IBattlerAttribute[];
	modSlots: IItemModSlot[];
	tags: number[];
	grantedSkillId?: number;
	retiredAt?: string;
}

export interface IItemMod {
	id: number;
	name: string;
	description: string;
	itemModTypeId: EItemModType;
	rarityId: ERarity;
	attributes: IBattlerAttribute[];
	tags: number[];
	retiredAt?: string;
}

export interface IItemModSlot {
	id: number;
	itemId: number;
	itemModSlotTypeId: EItemModType;
}

export interface IPath {
	id: number;
	name: string;
	description: string;
	falloffBase: number;
	retiredAt?: string;
	contributions: ISkillPathContribution[];
}

export interface IProficiency {
	id: number;
	name: string;
	description: string;
	iconPath: string;
	word: string;
	pronunciation: string;
	translation: string;
	pathId: number;
	pathOrdinal: number;
	maxLevel: number;
	baseXp: number;
	xpGrowth: number;
	seedSkillId?: number;
	retiredAt?: string;
	levelModifiers: IProficiencyLevelModifier[];
	levelRewards: IProficiencyLevelReward[];
	prerequisiteIds: number[];
}

export interface IProficiencyLevelModifier {
	level: number;
	attributeId: EAttribute;
	modifierTypeId: EModifierType;
	amount: number;
}

export interface IProficiencyLevelReward {
	level: number;
	rewardSkillId: number;
}

export interface ISignaturePassive {
	attributeId: EAttribute;
	amount: number;
	scalingAttributeId?: EAttribute;
	scalingAmount: number;
	modifierType: EModifierType;
}

export interface ISkill {
	id: number;
	name: string;
	baseDamage: number;
	damageMultipliers: IAttributeMultiplier[];
	effects: ISkillEffect[];
	description: string;
	cooldownMs: number;
	iconPath: string;
	rarityId: ERarity;
	acquisition: ESkillAcquisition;
	retiredAt?: string;
}

export interface ISkillEffect {
	id: number;
	target: ESkillEffectTarget;
	attributeId: EAttribute;
	modifierTypeId: EModifierType;
	amount: number;
	durationMs: number;
	scalingAttributeId: EAttribute;
	scalingAmount: number;
}

export interface ISkillPathContribution {
	skillId: number;
	homeTier: number;
	weight: number;
}

export interface ITag {
	id: number;
	name: string;
	tagCategoryId: number;
}

export interface ITagCategory {
	id: number;
	name: string;
}

export interface IZone {
	id: number;
	name: string;
	description: string;
	order: number;
	levelMin: number;
	levelMax: number;
	bossEnemyId?: number;
	bossLevel: number;
	unlockChallengeId?: number;
	retiredAt?: string;
}

export interface IZoneEnemy {
	enemyId: number;
	weight: number;
}