// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	EAttribute,
	EChallengeType,
	EEntityType,
	EItemCategory,
	EItemModType,
	ERarity,
	EStatisticType
} from '../';

export interface IAttributeDistribution {
	attributeId: EAttribute;
	baseAmount: number;
	amountPerLevel: number;
}

export interface IAttributeMultiplier {
	attributeId: EAttribute;
	multiplier: number;
}

export interface IBattlerAttribute {
	attributeId: EAttribute;
	amount: number;
}

export interface IChallenge {
	id: number;
	name: string;
	description: string;
	challengeTypeId: EChallengeType;
	statisticType?: EStatisticType;
	entityType: EEntityType;
	targetEntityId?: number;
	progressGoal: number;
	rewardItemId?: number;
	rewardItemModId?: number;
}

export interface IEnemy {
	id: number;
	name: string;
	isBoss: boolean;
	attributeDistribution: IAttributeDistribution[];
	skillPool: number[];
	spawns: IEnemySpawn[];
}

export interface IEnemySpawn {
	zoneId: number;
	weight: number;
}

export interface IItem {
	id: number;
	name: string;
	description: string;
	itemCategoryId: EItemCategory;
	rarityId: ERarity;
	iconPath: string;
	attributes: IBattlerAttribute[];
	modSlots: IItemModSlot[];
	tags: number[];
}

export interface IItemCategory {
	id: number;
	name: string;
}

export interface IItemMod {
	id: number;
	name: string;
	description: string;
	itemModTypeId: EItemModType;
	rarityId: ERarity;
	attributes: IBattlerAttribute[];
	tags: number[];
}

export interface IItemModSlot {
	id: number;
	itemId: number;
	itemModSlotTypeId: EItemModType;
}

export interface IItemModType {
	id: number;
	name: string;
}

export interface ISkill {
	id: number;
	name: string;
	baseDamage: number;
	damageMultipliers: IAttributeMultiplier[];
	description: string;
	cooldownMs: number;
	iconPath: string;
}

export interface ITag {
	id: number;
	name: string;
	tagCategoryId: number;
}

export interface ITagCategory {
	id: number;
	name: string;
}

export interface IZone {
	id: number;
	name: string;
	description: string;
	order: number;
	levelMin: number;
	levelMax: number;
	bossEnemyId?: number;
	bossLevel: number;
	unlockChallengeId?: number;
}

export interface IZoneEnemy {
	enemyId: number;
	weight: number;
}