// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { IBattlerAttribute } from '../';

export interface IBattleLostResponse {
	cooldown: number;
}

export interface IChallengeBossRequest {
	zoneId?: number;
}

export interface IDefeatEnemyRequest {
	timestamp: number;
}

export interface IDefeatEnemyResponse {
	cooldown: number;
	rewards?: IDefeatRewards;
}

export interface IDefeatRewards {
	expReward: number;
	newLevel: number;
	newExp: number;
	statPointsGained: number;
	statPointsUsed: number;
}

export interface IEnemyInstance {
	id: number;
	level: number;
	attributes: IBattlerAttribute[];
	seed: number;
	selectedSkills: number[];
}

export interface INewEnemyModel {
	cooldown?: number;
	enemyInstance?: IEnemyInstance;
}

export interface INewEnemyRequest {
	newZoneId?: number;
}