// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	ELogType,
	IAttributeDistribution,
	IBattlerAttribute,
	IInventoryData,
	ISignaturePassive
} from '../';

export interface ILoginCredentials {
	username: string;
	password: string;
}

export interface ILogPreference {
	id: ELogType;
	enabled: boolean;
}

export interface IPlayerData {
	id: number;
	name: string;
	level: number;
	exp: number;
	attributes: IBattlerAttribute[];
	unlockedSkills: IUnlockedSkill[];
	currentZone: number;
	statPointsGained: number;
	statPointsUsed: number;
	logPreferences: ILogPreference[];
	inventoryData: IInventoryData;
	lockedBaseDistribution: IAttributeDistribution[];
	signaturePassive: ISignaturePassive;
}

export interface IUnlockedSkill {
	skillId: number;
	selected: boolean;
	order?: number;
}