// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	EChallengeGoalComparison,
	EChallengeType,
	EEntityType,
	EStatisticType
} from '../';

export interface IChallengeCompletedModel {
	challengeId: number;
	rewardItemId?: number;
	rewardItemModId?: number;
}

export interface IChallengeType {
	id: EChallengeType;
	statisticType?: IStatisticType;
	goalComparison: EChallengeGoalComparison;
	name: string;
}

export interface IOfflineProgressModel {
	awayMs: number;
	autoChallengeBoss: boolean;
	zoneId: number;
	battlesWon: number;
	battlesLost: number;
	battlesDrawn: number;
	totalExp: number;
	levelsGained: number;
	statPointsGained: number;
	hasProgress: boolean;
	completedChallenges: IChallengeCompletedModel[];
	proficiencyGains: IProficiencyXpResultModel[];
	openedProficiencies: IProficiencyOpenedModel[];
}

export interface IPlayerChallenge {
	challengeId: number;
	progress: number;
	completed: boolean;
	completedAt?: string;
}

export interface IPlayerProficiency {
	proficiencyId: number;
	level: number;
	xp: number;
}

export interface IPlayerStatistic {
	statisticTypeId: EStatisticType;
	entityId?: number;
	value: number;
}

export interface IProficiencyOpenedModel {
	proficiencyId: number;
}

export interface IProficiencyXpGainedModel {
	proficiencies: IProficiencyXpResultModel[];
	opened: IProficiencyOpenedModel[];
}

export interface IProficiencyXpResultModel {
	proficiencyId: number;
	xpGained: number;
	newLevel: number;
	newXp: number;
	milestonesCrossed: number[];
	grantedSkillIds: number[];
}

export interface IStatisticType {
	id: EStatisticType;
	entityType: EEntityType;
	bossOnly: boolean;
	name: string;
}