// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type { IAdminUser } from '../';

export interface IAdminUserSearchResults {
	users: IAdminUser[];
	totalCount: number;
	page: number;
	pageSize: number;
}

export interface ISetUserRolesData {
	userId: number;
	roleIds: number[];
}

export interface IUserActionData {
	userId: number;
}