// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	IApplyModRequest,
	IAttribute,
	IAttributeUpdate,
	IBattleLostRequest,
	IBattleLostResponse,
	IChallenge,
	IChallengeBossRequest,
	IChallengeCompletedModel,
	IChallengeType,
	IClass,
	IDefeatEnemyRequest,
	IDefeatEnemyResponse,
	IEnemy,
	IEquipItemResponse,
	IEquipRequest,
	IItem,
	IItemMod,
	ILesson,
	ILogPreference,
	INewEnemyModel,
	INewEnemyRequest,
	IOfflineProgressModel,
	IPath,
	IPlayerChallenge,
	IPlayerProficiency,
	IPlayerStatistic,
	IProficiency,
	IProficiencyXpGainedModel,
	IReferenceDataVersion,
	IRemoveModRequest,
	IServerCommandFailedModel,
	ISetItemFavoriteRequest,
	ISkill,
	ISkillRecipe,
	IStatisticType,
	ISynthesisResult,
	IUpdatePlayerStatsResponse,
	IZone
} from './';

export type ApiSocketResponseTypes = {
	'AccessRevoked': undefined;
	'ApplyMod': undefined;
	'BattleLost': IBattleLostResponse;
	'ChallengeBoss': INewEnemyModel;
	'ChallengeCompleted': IChallengeCompletedModel;
	'DefeatEnemy': IDefeatEnemyResponse;
	'EquipItem': IEquipItemResponse;
	'GetAttributes': IAttribute[];
	'GetChallenges': IChallenge[];
	'GetChallengeTypes': IChallengeType[];
	'GetClasses': IClass[];
	'GetEnemies': IEnemy[];
	'GetItemMods': IItemMod[];
	'GetItems': IItem[];
	'GetLessons': ILesson[];
	'GetOfflineProgress': IOfflineProgressModel;
	'GetPaths': IPath[];
	'GetPlayerChallenges': IPlayerChallenge[];
	'GetPlayerProficiencies': IPlayerProficiency[];
	'GetPlayerStatistics': IPlayerStatistic[];
	'GetProficiencies': IProficiency[];
	'GetReferenceDataVersions': IReferenceDataVersion[];
	'GetSkillRecipes': ISkillRecipe[];
	'GetSkills': ISkill[];
	'GetStatisticTypes': IStatisticType[];
	'GetZones': IZone[];
	'MarkLessonRead': undefined;
	'NewEnemy': INewEnemyModel;
	'ProficiencyXpGained': IProficiencyXpGainedModel;
	'RemoveMod': undefined;
	'SaveLogPreferences': undefined;
	'ServerCommandFailed': IServerCommandFailedModel;
	'SetAutoChallengeBoss': undefined;
	'SetItemFavorite': undefined;
	'SetSelectedSkills': undefined;
	'SocketReplaced': undefined;
	'SynthesizeSkill': ISynthesisResult;
	'UnequipItem': IEquipItemResponse;
	'UnlockLesson': undefined;
	'UpdatePlayerStats': IUpdatePlayerStatsResponse;
};

export type ApiSocketRequestTypes = {
	'ApplyMod': IApplyModRequest;
	'BattleLost': IBattleLostRequest;
	'ChallengeBoss': IChallengeBossRequest;
	'DefeatEnemy': IDefeatEnemyRequest;
	'EquipItem': IEquipRequest;
	'MarkLessonRead': number;
	'NewEnemy': INewEnemyRequest;
	'RemoveMod': IRemoveModRequest;
	'SaveLogPreferences': ILogPreference[];
	'SetAutoChallengeBoss': boolean;
	'SetItemFavorite': ISetItemFavoriteRequest;
	'SetSelectedSkills': number[];
	'SynthesizeSkill': number;
	'UnequipItem': IEquipRequest;
	'UnlockLesson': number;
	'UpdatePlayerStats': IAttributeUpdate[];
};

export type ApiSocketCommand = keyof ApiSocketResponseTypes;

export type ApiSocketCommandWithRequest = keyof ApiSocketRequestTypes;

export type ApiSocketCommandNoRequest = Exclude<ApiSocketCommand, ApiSocketCommandWithRequest>;

export type ApiSocketResponseType = ApiSocketResponseTypes[ApiSocketCommand];