// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	IAttribute,
	IBattleLostResponse,
	IChallenge,
	IChallengeBossRequest,
	IChallengeType,
	IDefeatEnemyRequest,
	IDefeatEnemyResponse,
	IEnemy,
	IItem,
	IItemMod,
	ILogPreference,
	INewEnemyModel,
	INewEnemyRequest,
	IReferenceDataVersion,
	ISetItemFavoriteRequest,
	ISkill,
	IStatisticType,
	IZone
} from './';

export type ApiSocketResponseTypes = {
	'BattleLost': IBattleLostResponse;
	'ChallengeBoss': INewEnemyModel;
	'DefeatEnemy': IDefeatEnemyResponse;
	'GetAttributes': IAttribute[];
	'GetChallenges': IChallenge[];
	'GetChallengeTypes': IChallengeType[];
	'GetEnemies': IEnemy[];
	'GetItemMods': IItemMod[];
	'GetItems': IItem[];
	'GetReferenceDataVersions': IReferenceDataVersion[];
	'GetSkills': ISkill[];
	'GetStatisticTypes': IStatisticType[];
	'GetZones': IZone[];
	'NewEnemy': INewEnemyModel;
	'SaveLogPreferences': undefined;
	'SetItemFavorite': undefined;
	'SocketReplaced': undefined;
};

export type ApiSocketRequestTypes = {
	'ChallengeBoss': IChallengeBossRequest;
	'DefeatEnemy': IDefeatEnemyRequest;
	'NewEnemy': INewEnemyRequest;
	'SaveLogPreferences': ILogPreference[];
	'SetItemFavorite': ISetItemFavoriteRequest;
};

export type ApiSocketCommand = keyof ApiSocketResponseTypes;

export type ApiSocketCommandWithRequest = keyof ApiSocketRequestTypes;

export type ApiSocketCommandNoRequest = Exclude<ApiSocketCommand, ApiSocketCommandWithRequest>;

export type ApiSocketResponseType = ApiSocketResponseTypes[ApiSocketCommand];