// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	IActiveSessionResult,
	IAddEditAttributesData,
	IAdminUserSearchResults,
	IAuthTokens,
	IChallenge,
	IChange,
	IDeviceInfoRequest,
	IEnemy,
	IItem,
	IItemMod,
	IItemModSlot,
	ILoginCredentials,
	ILoginResult,
	IPlayerChallenge,
	IPlayerData,
	IPlayerStatistic,
	IRefreshRequest,
	IRole,
	ISetEnemyAttributeDistributions,
	ISetEnemySkillsData,
	ISetEnemySpawnsData,
	ISetSkillEffectsData,
	ISetTagsData,
	ISetUserRolesData,
	ISetZoneEnemiesData,
	ISkill,
	ITag,
	ITagCategory,
	IUserActionData,
	IZone
} from './';

export type ApiResponseTypes = {
	'AdminTools/AddEditChallenges': undefined;
	'AdminTools/AddEditEnemies': undefined;
	'AdminTools/AddEditItemAttributes': undefined;
	'AdminTools/AddEditItemModAttributes': undefined;
	'AdminTools/AddEditItemMods': undefined;
	'AdminTools/AddEditItemModSlots': undefined;
	'AdminTools/AddEditItems': undefined;
	'AdminTools/AddEditSkills': undefined;
	'AdminTools/AddEditTags': undefined;
	'AdminTools/AddEditZones': undefined;
	'AdminTools/ArchiveUser': undefined;
	'AdminTools/BanUser': undefined;
	'AdminTools/GetRoles': IRole[];
	'AdminTools/GetUsers': IAdminUserSearchResults;
	'AdminTools/SetEnemyAttributeDistributions': undefined;
	'AdminTools/SetEnemySkills': undefined;
	'AdminTools/SetEnemySpawns': undefined;
	'AdminTools/SetSkillEffects': undefined;
	'AdminTools/SetSkillMultipliers': undefined;
	'AdminTools/SetTagsForItem': undefined;
	'AdminTools/SetTagsForItemMod': undefined;
	'AdminTools/SetUserRoles': undefined;
	'AdminTools/SetZoneEnemies': undefined;
	'Challenges/Player': IPlayerChallenge[];
	'Login': ILoginResult;
	'Login/ActiveSession': IActiveSessionResult;
	'Login/CreateAccount': undefined;
	'Login/DeviceInfo': undefined;
	'Login/Logout': undefined;
	'Login/Refresh': IAuthTokens;
	'Login/Status': IPlayerData;
	'Player': IPlayerData;
	'Statistics': IPlayerStatistic[];
	'Tags': ITag[];
	'Tags/TagCategories': ITagCategory[];
};

export type ApiRequestTypes = {
	'AdminTools/AddEditChallenges': IChange<IChallenge>[];
	'AdminTools/AddEditEnemies': IChange<IEnemy>[];
	'AdminTools/AddEditItemAttributes': IAddEditAttributesData;
	'AdminTools/AddEditItemModAttributes': IAddEditAttributesData;
	'AdminTools/AddEditItemMods': IChange<IItemMod>[];
	'AdminTools/AddEditItemModSlots': IChange<IItemModSlot>[];
	'AdminTools/AddEditItems': IChange<IItem>[];
	'AdminTools/AddEditSkills': IChange<ISkill>[];
	'AdminTools/AddEditTags': IChange<ITag>[];
	'AdminTools/AddEditZones': IChange<IZone>[];
	'AdminTools/ArchiveUser': IUserActionData;
	'AdminTools/BanUser': IUserActionData;
	'AdminTools/GetUsers': { search?: string, roleId?: number, archived?: boolean, page?: number, pageSize?: number } | undefined;
	'AdminTools/SetEnemyAttributeDistributions': ISetEnemyAttributeDistributions;
	'AdminTools/SetEnemySkills': ISetEnemySkillsData;
	'AdminTools/SetEnemySpawns': ISetEnemySpawnsData;
	'AdminTools/SetSkillEffects': ISetSkillEffectsData;
	'AdminTools/SetSkillMultipliers': IAddEditAttributesData;
	'AdminTools/SetTagsForItem': ISetTagsData;
	'AdminTools/SetTagsForItemMod': ISetTagsData;
	'AdminTools/SetUserRoles': ISetUserRolesData;
	'AdminTools/SetZoneEnemies': ISetZoneEnemiesData;
	'Login': ILoginCredentials;
	'Login/CreateAccount': ILoginCredentials;
	'Login/DeviceInfo': IDeviceInfoRequest;
	'Login/Logout': IRefreshRequest;
	'Login/Refresh': IRefreshRequest;
};

export type ApiEndpoint = keyof ApiResponseTypes;

export type ApiEndpointOptionalRequest = {
	[K in keyof ApiRequestTypes]: undefined extends ApiRequestTypes[K] ? K : never;
}[keyof ApiRequestTypes];

export type ApiEndpointWithRequest = keyof ApiRequestTypes;

export type ApiEndpointNoRequest = ApiEndpointOptionalRequest | Exclude<ApiEndpoint, ApiEndpointWithRequest>;

export type ApiResponseType = ApiResponseTypes[ApiEndpoint];