// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import type {
	IActiveSessionResult,
	IAddEditAttributesData,
	IAdminUserSearchResults,
	IAuthTokens,
	IChallenge,
	IChange,
	IClass,
	IContentHealthReport,
	ICreatableClass,
	ICreateAccountRequest,
	ICreatePlayerRequest,
	IDeadLetterInspection,
	IDeadLetterReplayResult,
	IDeviceInfoRequest,
	IEnemy,
	IItem,
	IItemMod,
	IItemModSlot,
	ILesson,
	ILoginCredentials,
	ILoginResult,
	IPath,
	IPlayerData,
	IPlayerSummary,
	IProficiency,
	IRefreshRequest,
	IReplayDeadLettersData,
	IRole,
	ISelectPlayerRequest,
	ISelectPlayerResult,
	ISetClassAttributeDistributionsData,
	ISetClassStarterEquipmentData,
	ISetClassStarterSkillsData,
	ISetEnemyAttributeDistributions,
	ISetEnemySkillsData,
	ISetEnemySpawnsData,
	ISetLessonStepsData,
	ISetProficiencyModifiersData,
	ISetProficiencyPrerequisitesData,
	ISetProficiencyRewardsData,
	ISetSkillEffectsData,
	ISetSkillPortionsData,
	ISetSkillRecipeConditionsData,
	ISetSkillRecipeInputsData,
	ISetTagsData,
	ISetUserRolesData,
	ISetZoneEnemiesData,
	ISkill,
	ISkillRecipe,
	ITag,
	ITagCategory,
	IUserActionData,
	IZone
} from './';

export type ApiResponseTypes = {
	'AdminTools/AddEditChallenges': undefined;
	'AdminTools/AddEditClasses': undefined;
	'AdminTools/AddEditEnemies': undefined;
	'AdminTools/AddEditItemAttributes': undefined;
	'AdminTools/AddEditItemModAttributes': undefined;
	'AdminTools/AddEditItemMods': undefined;
	'AdminTools/AddEditItemModSlots': undefined;
	'AdminTools/AddEditItems': undefined;
	'AdminTools/AddEditLessons': undefined;
	'AdminTools/AddEditPaths': undefined;
	'AdminTools/AddEditProficiencies': undefined;
	'AdminTools/AddEditSkillRecipes': undefined;
	'AdminTools/AddEditSkills': undefined;
	'AdminTools/AddEditTags': undefined;
	'AdminTools/AddEditZones': undefined;
	'AdminTools/ArchiveUser': undefined;
	'AdminTools/BanUser': undefined;
	'AdminTools/GetContentHealth': IContentHealthReport;
	'AdminTools/GetPlayerUpdateDeadLetters': IDeadLetterInspection;
	'AdminTools/GetRoles': IRole[];
	'AdminTools/GetSocketCommandDeadLetters': IDeadLetterInspection;
	'AdminTools/GetUsers': IAdminUserSearchResults;
	'AdminTools/ReplayPlayerUpdateDeadLetters': IDeadLetterReplayResult;
	'AdminTools/ReplaySocketCommandDeadLetters': IDeadLetterReplayResult;
	'AdminTools/SetClassAttributeDistributions': undefined;
	'AdminTools/SetClassStarterEquipment': undefined;
	'AdminTools/SetClassStarterSkills': undefined;
	'AdminTools/SetEnemyAttributeDistributions': undefined;
	'AdminTools/SetEnemySkills': undefined;
	'AdminTools/SetEnemySpawns': undefined;
	'AdminTools/SetLessonSteps': undefined;
	'AdminTools/SetProficiencyModifiers': undefined;
	'AdminTools/SetProficiencyPrerequisites': undefined;
	'AdminTools/SetProficiencyRewards': undefined;
	'AdminTools/SetSkillEffects': undefined;
	'AdminTools/SetSkillMultipliers': undefined;
	'AdminTools/SetSkillPortions': undefined;
	'AdminTools/SetSkillRecipeConditions': undefined;
	'AdminTools/SetSkillRecipeInputs': undefined;
	'AdminTools/SetTagsForItem': undefined;
	'AdminTools/SetTagsForItemMod': undefined;
	'AdminTools/SetUserRoles': undefined;
	'AdminTools/SetZoneEnemies': undefined;
	'Login': ILoginResult;
	'Login/ActiveSession': IActiveSessionResult;
	'Login/CharacterCreationData': ICreatableClass[];
	'Login/CreateAccount': undefined;
	'Login/CreatePlayer': IPlayerSummary;
	'Login/DeviceInfo': undefined;
	'Login/Logout': undefined;
	'Login/Players': IPlayerSummary[];
	'Login/Refresh': IAuthTokens;
	'Login/SelectPlayer': ISelectPlayerResult;
	'Login/Status': IPlayerData;
	'Login/SwitchPlayer': ISelectPlayerResult;
	'Tags': ITag[];
	'Tags/TagCategories': ITagCategory[];
};

export type ApiRequestTypes = {
	'AdminTools/AddEditChallenges': IChange<IChallenge>[];
	'AdminTools/AddEditClasses': IChange<IClass>[];
	'AdminTools/AddEditEnemies': IChange<IEnemy>[];
	'AdminTools/AddEditItemAttributes': IAddEditAttributesData;
	'AdminTools/AddEditItemModAttributes': IAddEditAttributesData;
	'AdminTools/AddEditItemMods': IChange<IItemMod>[];
	'AdminTools/AddEditItemModSlots': IChange<IItemModSlot>[];
	'AdminTools/AddEditItems': IChange<IItem>[];
	'AdminTools/AddEditLessons': IChange<ILesson>[];
	'AdminTools/AddEditPaths': IChange<IPath>[];
	'AdminTools/AddEditProficiencies': IChange<IProficiency>[];
	'AdminTools/AddEditSkillRecipes': IChange<ISkillRecipe>[];
	'AdminTools/AddEditSkills': IChange<ISkill>[];
	'AdminTools/AddEditTags': IChange<ITag>[];
	'AdminTools/AddEditZones': IChange<IZone>[];
	'AdminTools/ArchiveUser': IUserActionData;
	'AdminTools/BanUser': IUserActionData;
	'AdminTools/GetPlayerUpdateDeadLetters': { max?: number } | undefined;
	'AdminTools/GetSocketCommandDeadLetters': { max?: number } | undefined;
	'AdminTools/GetUsers': { search?: string, roleId?: number, archived?: boolean, page?: number, pageSize?: number } | undefined;
	'AdminTools/ReplayPlayerUpdateDeadLetters': IReplayDeadLettersData;
	'AdminTools/ReplaySocketCommandDeadLetters': IReplayDeadLettersData;
	'AdminTools/SetClassAttributeDistributions': ISetClassAttributeDistributionsData;
	'AdminTools/SetClassStarterEquipment': ISetClassStarterEquipmentData;
	'AdminTools/SetClassStarterSkills': ISetClassStarterSkillsData;
	'AdminTools/SetEnemyAttributeDistributions': ISetEnemyAttributeDistributions;
	'AdminTools/SetEnemySkills': ISetEnemySkillsData;
	'AdminTools/SetEnemySpawns': ISetEnemySpawnsData;
	'AdminTools/SetLessonSteps': ISetLessonStepsData;
	'AdminTools/SetProficiencyModifiers': ISetProficiencyModifiersData;
	'AdminTools/SetProficiencyPrerequisites': ISetProficiencyPrerequisitesData[];
	'AdminTools/SetProficiencyRewards': ISetProficiencyRewardsData;
	'AdminTools/SetSkillEffects': ISetSkillEffectsData;
	'AdminTools/SetSkillMultipliers': IAddEditAttributesData;
	'AdminTools/SetSkillPortions': ISetSkillPortionsData;
	'AdminTools/SetSkillRecipeConditions': ISetSkillRecipeConditionsData;
	'AdminTools/SetSkillRecipeInputs': ISetSkillRecipeInputsData;
	'AdminTools/SetTagsForItem': ISetTagsData;
	'AdminTools/SetTagsForItemMod': ISetTagsData;
	'AdminTools/SetUserRoles': ISetUserRolesData;
	'AdminTools/SetZoneEnemies': ISetZoneEnemiesData;
	'Login': ILoginCredentials;
	'Login/CreateAccount': ICreateAccountRequest;
	'Login/CreatePlayer': ICreatePlayerRequest;
	'Login/DeviceInfo': IDeviceInfoRequest;
	'Login/Logout': IRefreshRequest;
	'Login/Refresh': IRefreshRequest;
	'Login/SelectPlayer': ISelectPlayerRequest;
	'Login/SwitchPlayer': ISelectPlayerRequest;
};

export type ApiEndpoint = keyof ApiResponseTypes;

export type ApiEndpointOptionalRequest = {
	[K in keyof ApiRequestTypes]: undefined extends ApiRequestTypes[K] ? K : never;
}[keyof ApiRequestTypes];

export type ApiEndpointWithRequest = keyof ApiRequestTypes;

export type ApiEndpointNoRequest = ApiEndpointOptionalRequest | Exclude<ApiEndpoint, ApiEndpointWithRequest>;

export type ApiResponseType = ApiResponseTypes[ApiEndpoint];