// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import { EAttribute, EAttributeModifierSource, EModifierType } from './enums.ts';

export const STATIC_ATTRIBUTE_MODIFIERS = [
	{ attribute: EAttribute.CooldownRecovery, amount: 0.4, type: EModifierType.Additive, source: EAttributeModifierSource.Derived, derivedSource: EAttribute.Agility },
	{ attribute: EAttribute.CooldownRecovery, amount: 0.1, type: EModifierType.Additive, source: EAttributeModifierSource.Derived, derivedSource: EAttribute.Dexterity },
	{ attribute: EAttribute.Defense, amount: 2, type: EModifierType.Additive, source: EAttributeModifierSource.BaseValue },
	{ attribute: EAttribute.Defense, amount: 1, type: EModifierType.Additive, source: EAttributeModifierSource.Derived, derivedSource: EAttribute.Endurance },
	{ attribute: EAttribute.Defense, amount: 0.5, type: EModifierType.Additive, source: EAttributeModifierSource.Derived, derivedSource: EAttribute.Agility },
	{ attribute: EAttribute.MaxHealth, amount: 50, type: EModifierType.Additive, source: EAttributeModifierSource.BaseValue },
	{ attribute: EAttribute.MaxHealth, amount: 20, type: EModifierType.Additive, source: EAttributeModifierSource.Derived, derivedSource: EAttribute.Endurance },
	{ attribute: EAttribute.MaxHealth, amount: 5, type: EModifierType.Additive, source: EAttributeModifierSource.Derived, derivedSource: EAttribute.Strength },
] as const;