// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import { EAttribute, EDamageType, EDamageTypeKey } from './enums.ts';

export const DAMAGE_TYPE_APPLIES = {
	[EDamageType.Physical]: [EDamageTypeKey.Physical],
	[EDamageType.Fire]: [EDamageTypeKey.Fire, EDamageTypeKey.Elemental],
	[EDamageType.Water]: [EDamageTypeKey.Water, EDamageTypeKey.Elemental],
	[EDamageType.Earth]: [EDamageTypeKey.Earth, EDamageTypeKey.Elemental],
	[EDamageType.Wind]: [EDamageTypeKey.Wind, EDamageTypeKey.Elemental],
	[EDamageType.Bleed]: [EDamageTypeKey.Bleed, EDamageTypeKey.Dot],
	[EDamageType.Poison]: [EDamageTypeKey.Poison, EDamageTypeKey.Dot],
	[EDamageType.Burn]: [EDamageTypeKey.Burn, EDamageTypeKey.Fire, EDamageTypeKey.Elemental, EDamageTypeKey.Dot],
} as const;

export const DAMAGE_TYPE_KEY_ATTRIBUTES = {
	[EDamageTypeKey.Physical]: { amplification: EAttribute.PhysicalAmplification, resistance: EAttribute.PhysicalResistance },
	[EDamageTypeKey.Fire]: { amplification: EAttribute.FireAmplification, resistance: EAttribute.FireResistance },
	[EDamageTypeKey.Water]: { amplification: EAttribute.WaterAmplification, resistance: EAttribute.WaterResistance },
	[EDamageTypeKey.Earth]: { amplification: EAttribute.EarthAmplification, resistance: EAttribute.EarthResistance },
	[EDamageTypeKey.Wind]: { amplification: EAttribute.WindAmplification, resistance: EAttribute.WindResistance },
	[EDamageTypeKey.Bleed]: { amplification: EAttribute.BleedAmplification, resistance: EAttribute.BleedResistance },
	[EDamageTypeKey.Poison]: { amplification: EAttribute.PoisonAmplification, resistance: EAttribute.PoisonResistance },
	[EDamageTypeKey.Burn]: { amplification: EAttribute.BurnAmplification, resistance: EAttribute.BurnResistance },
	[EDamageTypeKey.Elemental]: { amplification: EAttribute.ElementalAmplification, resistance: EAttribute.ElementalResistance },
	[EDamageTypeKey.Dot]: { amplification: EAttribute.DotAmplification, resistance: EAttribute.DotResistance },
} as const;