// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

import { EAttribute, EDamageType, EDamageTypeKey } from './enums.ts';

export const DAMAGE_TYPE_APPLIES = {
	[EDamageType.Physical]: [EDamageTypeKey.Physical],
	[EDamageType.Fire]: [EDamageTypeKey.Fire, EDamageTypeKey.Elemental],
	[EDamageType.Water]: [EDamageTypeKey.Water, EDamageTypeKey.Elemental],
	[EDamageType.Earth]: [EDamageTypeKey.Earth, EDamageTypeKey.Elemental],
	[EDamageType.Wind]: [EDamageTypeKey.Wind, EDamageTypeKey.Elemental],
	[EDamageType.Bleed]: [EDamageTypeKey.Bleed, EDamageTypeKey.Dot],
	[EDamageType.Poison]: [EDamageTypeKey.Poison, EDamageTypeKey.Dot],
	[EDamageType.Burn]: [EDamageTypeKey.Burn, EDamageTypeKey.Fire, EDamageTypeKey.Elemental, EDamageTypeKey.Dot],
	[EDamageType.Sword]: [EDamageTypeKey.Sword, EDamageTypeKey.Physical],
	[EDamageType.Axe]: [EDamageTypeKey.Axe, EDamageTypeKey.Physical],
	[EDamageType.Bow]: [EDamageTypeKey.Bow, EDamageTypeKey.Physical],
	[EDamageType.Club]: [EDamageTypeKey.Club, EDamageTypeKey.Physical],
	[EDamageType.Dagger]: [EDamageTypeKey.Dagger, EDamageTypeKey.Physical],
	[EDamageType.Unarmed]: [EDamageTypeKey.Unarmed, EDamageTypeKey.Physical],
} as const;

export const DAMAGE_TYPE_KEY_ATTRIBUTES = {
	[EDamageTypeKey.Physical]: { amplification: EAttribute.PhysicalAmplification, resistance: EAttribute.PhysicalResistance },
	[EDamageTypeKey.Fire]: { amplification: EAttribute.FireAmplification, resistance: EAttribute.FireResistance },
	[EDamageTypeKey.Water]: { amplification: EAttribute.WaterAmplification, resistance: EAttribute.WaterResistance },
	[EDamageTypeKey.Earth]: { amplification: EAttribute.EarthAmplification, resistance: EAttribute.EarthResistance },
	[EDamageTypeKey.Wind]: { amplification: EAttribute.WindAmplification, resistance: EAttribute.WindResistance },
	[EDamageTypeKey.Bleed]: { amplification: EAttribute.BleedAmplification, resistance: EAttribute.BleedResistance },
	[EDamageTypeKey.Poison]: { amplification: EAttribute.PoisonAmplification, resistance: EAttribute.PoisonResistance },
	[EDamageTypeKey.Burn]: { amplification: EAttribute.BurnAmplification, resistance: EAttribute.BurnResistance },
	[EDamageTypeKey.Elemental]: { amplification: EAttribute.ElementalAmplification, resistance: EAttribute.ElementalResistance },
	[EDamageTypeKey.Dot]: { amplification: EAttribute.DotAmplification, resistance: EAttribute.DotResistance },
	[EDamageTypeKey.Sword]: { amplification: EAttribute.SwordAmplification, resistance: null },
	[EDamageTypeKey.Axe]: { amplification: EAttribute.AxeAmplification, resistance: null },
	[EDamageTypeKey.Bow]: { amplification: EAttribute.BowAmplification, resistance: null },
	[EDamageTypeKey.Club]: { amplification: EAttribute.ClubAmplification, resistance: null },
	[EDamageTypeKey.Dagger]: { amplification: EAttribute.DaggerAmplification, resistance: null },
	[EDamageTypeKey.Unarmed]: { amplification: EAttribute.UnarmedAmplification, resistance: null },
} as const;

export const DAMAGE_TYPE_DOT_ACCUMULATORS = [
	{ type: EDamageType.Bleed, accumulator: EAttribute.BleedDamagePerSecond },
	{ type: EDamageType.Poison, accumulator: EAttribute.PoisonDamagePerSecond },
	{ type: EDamageType.Burn, accumulator: EAttribute.BurnDamagePerSecond },
] as const;