// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

export enum EActivityKey {
	Physical = 0,
	Fire = 1,
	Water = 2,
	Earth = 3,
	Wind = 4,
	Bleed = 5,
	Poison = 6,
	Burn = 7,
	Elemental = 8,
	Dot = 9,
	Crit = 10,
	Dodge = 11,
	Heal = 12,
	Reflect = 13,
}

export enum EAttribute {
	Strength = 0,
	Endurance = 1,
	Intellect = 2,
	Agility = 3,
	Dexterity = 4,
	Luck = 5,
	MaxHealth = 6,
	Toughness = 7,
	CooldownRecovery = 8,
	/** @deprecated Drop system has been replaced by challenge-based unlocks. */
	DropBonus = 9,
	CriticalChance = 10,
	CriticalDamage = 11,
	DodgeChance = 12,
	BlockChance = 13,
	BlockReduction = 14,
	BleedDamagePerSecond = 15,
	HealthRegenPerSecond = 16,
	PhysicalAmplification = 17,
	PhysicalResistance = 18,
	FireAmplification = 19,
	FireResistance = 20,
	WaterAmplification = 21,
	WaterResistance = 22,
	EarthAmplification = 23,
	EarthResistance = 24,
	WindAmplification = 25,
	WindResistance = 26,
	BleedAmplification = 27,
	BleedResistance = 28,
	PoisonAmplification = 29,
	PoisonResistance = 30,
	BurnAmplification = 31,
	BurnResistance = 32,
	ElementalAmplification = 33,
	ElementalResistance = 34,
	DotAmplification = 35,
	DotResistance = 36,
	PoisonDamagePerSecond = 37,
	BurnDamagePerSecond = 38,
}

export enum EAttributeModifierSource {
	BaseValue = 1,
	PlayerStatPoints = 2,
	AttributeDistribution = 3,
	Derived = 4,
	Item = 5,
	ItemMod = 6,
	SkillEffect = 7,
	Proficiency = 8,
	Class = 9,
}

export enum EAttributeType {
	Primary = 1,
	Secondary = 2,
	Status = 3,
	Affinity = 4,
}

export enum EChallengeGoalComparison {
	AtLeast = 1,
	AtMost = 2,
}

export enum EChallengeType {
	EnemiesKilled = 1,
	BossesDefeated = 2,
	ZonesCleared = 3,
	TimeTrial = 4,
	LevelReached = 5,
	DamageDealt = 6,
	BattlesWon = 7,
	SkillsUsed = 8,
}

export enum EChangeType {
	Add = 0,
	Edit = 1,
	Delete = 2,
}

export enum EDamageType {
	Physical = 0,
	Fire = 1,
	Water = 2,
	Earth = 3,
	Wind = 4,
	Bleed = 5,
	Poison = 6,
	Burn = 7,
}

export enum EDamageTypeKey {
	Physical = 0,
	Fire = 1,
	Water = 2,
	Earth = 3,
	Wind = 4,
	Bleed = 5,
	Poison = 6,
	Burn = 7,
	Elemental = 8,
	Dot = 9,
}

export enum EDeadLetterReason {
	Malformed = 0,
	UnknownEventType = 1,
	Replayable = 2,
}

export enum EEntityType {
	None = 0,
	Enemy = 1,
	Zone = 2,
	Skill = 3,
}

export enum EEquipmentSlot {
	HelmSlot = 0,
	ChestSlot = 1,
	LegSlot = 2,
	BootSlot = 3,
	WeaponSlot = 4,
	AccessorySlot = 5,
}

export enum EItemCategory {
	Helm = 1,
	Chest = 2,
	Leg = 3,
	Boot = 4,
	Weapon = 5,
	Accessory = 6,
}

export enum EItemModType {
	Component = 1,
	Prefix = 2,
	Suffix = 3,
}

export enum ELogType {
	Damage = 1,
	Debug = 2,
	Exp = 3,
	LevelUp = 4,
	ItemFound = 5,
	EnemyDefeated = 6,
	SkillEffect = 7,
	Proficiency = 8,
}

export enum EModifierType {
	Additive = 1,
	Multiplicative = 2,
}

export enum ERarity {
	Common = 1,
	Uncommon = 2,
	Rare = 3,
	Epic = 4,
	Legendary = 5,
	Mythic = 6,
}

export enum ESkillAcquisition {
	None = 0,
	Player = 1,
	Item = 2,
	Enemy = 4,
	Synthesis = 8,
}

export enum ESkillEffectTarget {
	Self = 1,
	Opponent = 2,
}

export enum EStatisticType {
	EnemiesKilled = 1,
	BossesDefeated = 2,
	ZonesCleared = 3,
	DamageDealt = 4,
	HighestSingleAttackDamage = 5,
	DamageTaken = 6,
	DamageHealed = 7,
	EnemiesEncountered = 8,
	BattlesWon = 9,
	BattlesLost = 10,
	PlayerDeaths = 11,
	TotalBattleTime = 12,
	FastestVictory = 13,
	SkillsUsed = 14,
	BattlesAbandoned = 15,
	CriticalHits = 16,
	CriticalDamageDealt = 17,
	AttacksDodged = 18,
	DamageDodged = 19,
	AttacksBlocked = 20,
	DamageBlocked = 21,
}