// This file was automatically generated by Game.Api.CodeGen.
// Do not modify this file directly. Instead, modify the source C# code and regenerate the TypeScript files.

export const DEFAULT_MAX_BATTLE_MS = 120000;
export const EXP_PER_LEVEL = 100;
export const MAX_SELECTED_SKILLS = 4;
export const MS_PER_TICK = 40;
export const STAT_POINTS_PER_LEVEL = 6;