// <auto-generated />
using System;
using Game.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260529213216_AddEnemyIsBoss")]
    partial class AddEnemyIsBoss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.Infrastructure.Entities.AppliedMod", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemModSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemModId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ItemId", "ItemModSlotId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemModId");

                    b.HasIndex("ItemModSlotId");

                    b.ToTable("AppliedMods");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "A measure of one's raw physical force.",
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 1,
                            Description = "A measure of one's raw physical force.",
                            Name = "Endurance"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A measure of one's raw physical force.",
                            Name = "Intellect"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A measure of one's raw physical force.",
                            Name = "Agility"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A measure of one's raw physical force.",
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A measure of one's raw physical force.",
                            Name = "Luck"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A measure of one's raw physical force.",
                            Name = "Max Health"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A measure of one's raw physical force.",
                            Name = "Defense"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A measure of one's raw physical force.",
                            Name = "Cooldown Recovery"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A measure of one's raw physical force.",
                            Name = "Drop Bonus"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A measure of one's raw physical force.",
                            Name = "Critical Chance"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A measure of one's raw physical force.",
                            Name = "Critical Damage"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A measure of one's raw physical force.",
                            Name = "Dodge Chance"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A measure of one's raw physical force.",
                            Name = "Block Chance"
                        },
                        new
                        {
                            Id = 14,
                            Description = "A measure of one's raw physical force.",
                            Name = "Block Reduction"
                        });
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.AttributeDistribution", b =>
                {
                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AmountPerLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("EnemyId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributeDistributions");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 0L, null, 0L, null, null, null);

                    b.Property<int>("ChallengeTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RewardItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("RewardItemModId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RewardItemId");

                    b.HasIndex("RewardItemModId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 0L, null, 0L, null, null, null);

                    b.Property<bool>("IsBoss")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.EnemySkill", b =>
                {
                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("EnemyId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("EnemySkills");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.EquipmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("EquipmentSlots");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            ItemCategoryId = 1,
                            Name = "Helm Slot"
                        },
                        new
                        {
                            Id = 1,
                            ItemCategoryId = 2,
                            Name = "Chest Slot"
                        },
                        new
                        {
                            Id = 2,
                            ItemCategoryId = 3,
                            Name = "Leg Slot"
                        },
                        new
                        {
                            Id = 3,
                            ItemCategoryId = 4,
                            Name = "Boot Slot"
                        },
                        new
                        {
                            Id = 4,
                            ItemCategoryId = 5,
                            Name = "Weapon Slot"
                        },
                        new
                        {
                            Id = 5,
                            ItemCategoryId = 6,
                            Name = "Accessory Slot"
                        });
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 0L, null, 0L, null, null, null);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemAttribute", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("ItemId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("ItemAttributes");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Helm"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Boot"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Weapon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Accessory"
                        });
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemMod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 0L, null, 0L, null, null, null);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemModTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Removable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ItemModTypeId");

                    b.ToTable("ItemMods");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemModAttribute", b =>
                {
                    b.Property<int>("ItemModId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("ItemModId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("ItemModAttributes");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemModSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemModSlotTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemModSlotTypeId");

                    b.ToTable("ItemModSlots");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemModType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemModTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Component"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prefix"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Suffix"
                        });
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.LogPreference", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("LogSettingId")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "LogSettingId");

                    b.HasIndex("LogSettingId");

                    b.ToTable("LogPreferences");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.LogSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("LogSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultValue = false,
                            Name = "Damage"
                        },
                        new
                        {
                            Id = 2,
                            DefaultValue = false,
                            Name = "Debug"
                        },
                        new
                        {
                            Id = 3,
                            DefaultValue = false,
                            Name = "Exp"
                        },
                        new
                        {
                            Id = 4,
                            DefaultValue = false,
                            Name = "Level Up"
                        },
                        new
                        {
                            Id = 5,
                            DefaultValue = false,
                            Name = "Item Found"
                        },
                        new
                        {
                            Id = 6,
                            DefaultValue = false,
                            Name = "Enemy Defeated"
                        });
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StatPointsGained")
                        .HasColumnType("integer");

                    b.Property<int>("StatPointsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerAttribute", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("PlayerId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("PlayerAttributes");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerChallenge", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ChallengeId");

                    b.HasIndex("ChallengeId");

                    b.ToTable("PlayerChallenges");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerSkill", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PlayerSkills");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("StatisticTypeId")
                        .HasColumnType("integer");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StatisticTypeId");

                    b.HasIndex("PlayerId", "StatisticTypeId", "EntityId")
                        .IsUnique();

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 0L, null, 0L, null, null, null);

                    b.Property<decimal>("BaseDamage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("CooldownMs")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.SkillDamageMultiplier", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("SkillId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("SkillDamageMultipliers");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.StatisticType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("StatisticTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Enemies Killed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bosses Defeated"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zones Cleared"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Total Damage Dealt"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Highest Single Attack Damage"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Total Damage Taken"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Total Damage Healed"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Enemies Encountered"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Battles Won"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Battles Lost"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Player Deaths"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Total Battle Time Ms"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Fastest Victory Ms"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Total Skills Used"
                        });
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TagCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagCategoryId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TagCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Accessory"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Armor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Magical"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Material"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Modification"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Usage"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Weapon"
                        });
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.UnlockedItem", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipmentSlotId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UnlockedItems");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.UnlockedMod", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemModId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ItemModId");

                    b.HasIndex("ItemModId");

                    b.ToTable("UnlockedMods");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 0L, null, 0L, null, null, null);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LevelMax")
                        .HasColumnType("integer");

                    b.Property<int>("LevelMin")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ZoneEnemy", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("ZoneId", "EnemyId");

                    b.HasIndex("EnemyId");

                    b.ToTable("ZoneEnemies");
                });

            modelBuilder.Entity("ItemModTag", b =>
                {
                    b.Property<int>("ItemModsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ItemModsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ItemModTags", (string)null);
                });

            modelBuilder.Entity("ItemTag", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ItemTags", (string)null);
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.AppliedMod", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.ItemMod", "ItemMod")
                        .WithMany()
                        .HasForeignKey("ItemModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.ItemModSlot", "ItemModSlot")
                        .WithMany()
                        .HasForeignKey("ItemModSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("AppliedMods")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemMod");

                    b.Navigation("ItemModSlot");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.AttributeDistribution", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Attribute", "Attribute")
                        .WithMany("AttributeDistributions")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Enemy", "Enemy")
                        .WithMany("AttributeDistributions")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Challenge", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Item", "RewardItem")
                        .WithMany()
                        .HasForeignKey("RewardItemId");

                    b.HasOne("Game.Infrastructure.Entities.ItemMod", "RewardItemMod")
                        .WithMany()
                        .HasForeignKey("RewardItemModId");

                    b.Navigation("RewardItem");

                    b.Navigation("RewardItemMod");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.EnemySkill", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Enemy", "Enemy")
                        .WithMany("EnemySkills")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Skill", "Skill")
                        .WithMany("EnemySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.EquipmentSlot", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.ItemCategory", "ItemCategory")
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Item", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.ItemCategory", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemAttribute", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Attribute", "Attribute")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Item", "Item")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemMod", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.ItemModType", "ItemModType")
                        .WithMany("ItemMods")
                        .HasForeignKey("ItemModTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemModType");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemModAttribute", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Attribute", "Attribute")
                        .WithMany("ItemModAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.ItemMod", "ItemMod")
                        .WithMany("ItemModAttributes")
                        .HasForeignKey("ItemModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("ItemMod");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemModSlot", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Item", "Item")
                        .WithMany("ItemModSlots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.ItemModType", "ItemModSlotType")
                        .WithMany("ItemModSlots")
                        .HasForeignKey("ItemModSlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemModSlotType");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.LogPreference", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.LogSetting", "LogSetting")
                        .WithMany("LogPreferences")
                        .HasForeignKey("LogSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("LogPreferences")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogSetting");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Player", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerAttribute", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Attribute", "Attribute")
                        .WithMany("PlayerAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("PlayerAttributes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerChallenge", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("PlayerChallenges")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerSkill", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Skill", "Skill")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PlayerStatistic", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("PlayerStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.StatisticType", "StatisticType")
                        .WithMany("PlayerStatistics")
                        .HasForeignKey("StatisticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("StatisticType");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.SkillDamageMultiplier", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Attribute", "Attribute")
                        .WithMany("SkillDamageMultipliers")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Skill", "Skill")
                        .WithMany("SkillDamageMultipliers")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Tag", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.TagCategory", "TagCategory")
                        .WithMany("Tags")
                        .HasForeignKey("TagCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagCategory");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.UnlockedItem", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Item", "Item")
                        .WithMany("UnlockedItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("UnlockedItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.UnlockedMod", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.ItemMod", "ItemMod")
                        .WithMany("UnlockedMods")
                        .HasForeignKey("ItemModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Player", "Player")
                        .WithMany("UnlockedMods")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMod");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ZoneEnemy", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Enemy", "Enemy")
                        .WithMany("ZoneEnemies")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Zone", "Zone")
                        .WithMany("ZoneEnemies")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ItemModTag", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.ItemMod", null)
                        .WithMany()
                        .HasForeignKey("ItemModsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemTag", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Infrastructure.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Attribute", b =>
                {
                    b.Navigation("AttributeDistributions");

                    b.Navigation("ItemAttributes");

                    b.Navigation("ItemModAttributes");

                    b.Navigation("PlayerAttributes");

                    b.Navigation("SkillDamageMultipliers");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Enemy", b =>
                {
                    b.Navigation("AttributeDistributions");

                    b.Navigation("EnemySkills");

                    b.Navigation("ZoneEnemies");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Item", b =>
                {
                    b.Navigation("ItemAttributes");

                    b.Navigation("ItemModSlots");

                    b.Navigation("UnlockedItems");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemCategory", b =>
                {
                    b.Navigation("EquipmentSlots");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemMod", b =>
                {
                    b.Navigation("ItemModAttributes");

                    b.Navigation("UnlockedMods");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.ItemModType", b =>
                {
                    b.Navigation("ItemModSlots");

                    b.Navigation("ItemMods");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.LogSetting", b =>
                {
                    b.Navigation("LogPreferences");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Player", b =>
                {
                    b.Navigation("AppliedMods");

                    b.Navigation("LogPreferences");

                    b.Navigation("PlayerAttributes");

                    b.Navigation("PlayerChallenges");

                    b.Navigation("PlayerSkills");

                    b.Navigation("PlayerStatistics");

                    b.Navigation("UnlockedItems");

                    b.Navigation("UnlockedMods");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Skill", b =>
                {
                    b.Navigation("EnemySkills");

                    b.Navigation("PlayerSkills");

                    b.Navigation("SkillDamageMultipliers");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.StatisticType", b =>
                {
                    b.Navigation("PlayerStatistics");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.Zone", b =>
                {
                    b.Navigation("ZoneEnemies");
                });
#pragma warning restore 612, 618
        }
    }
}
