// <auto-generated />
using System;
using Game.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.Core.Entities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "A measure of one's raw physical force.",
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 1,
                            Description = "A measure of one's raw physical force.",
                            Name = "Endurance"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A measure of one's raw physical force.",
                            Name = "Intellect"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A measure of one's raw physical force.",
                            Name = "Agility"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A measure of one's raw physical force.",
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A measure of one's raw physical force.",
                            Name = "Luck"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A measure of one's raw physical force.",
                            Name = "Max Health"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A measure of one's raw physical force.",
                            Name = "Defense"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A measure of one's raw physical force.",
                            Name = "Cooldown Recovery"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A measure of one's raw physical force.",
                            Name = "Drop Bonus"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A measure of one's raw physical force.",
                            Name = "Critical Chance"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A measure of one's raw physical force.",
                            Name = "Critical Damage"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A measure of one's raw physical force.",
                            Name = "Dodge Chance"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A measure of one's raw physical force.",
                            Name = "Block Chance"
                        },
                        new
                        {
                            Id = 14,
                            Description = "A measure of one's raw physical force.",
                            Name = "Block Reduction"
                        });
                });

            modelBuilder.Entity("Game.Core.Entities.AttributeDistribution", b =>
                {
                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AmountPerLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("EnemyId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributeDistributions");
                });

            modelBuilder.Entity("Game.Core.Entities.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("Game.Core.Entities.EnemyDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DropRate")
                        .HasPrecision(9, 8)
                        .HasColumnType("numeric(9,8)");

                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("ItemId");

                    b.ToTable("EnemyDrops");
                });

            modelBuilder.Entity("Game.Core.Entities.EnemySkill", b =>
                {
                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("EnemyId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("EnemySkills");
                });

            modelBuilder.Entity("Game.Core.Entities.EquipmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("EquipmentSlots");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            ItemCategoryId = 1,
                            Name = "Helm Slot"
                        },
                        new
                        {
                            Id = 1,
                            ItemCategoryId = 2,
                            Name = "Chest Slot"
                        },
                        new
                        {
                            Id = 2,
                            ItemCategoryId = 3,
                            Name = "Leg Slot"
                        },
                        new
                        {
                            Id = 3,
                            ItemCategoryId = 4,
                            Name = "Boot Slot"
                        },
                        new
                        {
                            Id = 4,
                            ItemCategoryId = 5,
                            Name = "Weapon Slot"
                        },
                        new
                        {
                            Id = 5,
                            ItemCategoryId = 6,
                            Name = "Accessory Slot"
                        });
                });

            modelBuilder.Entity("Game.Core.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Equipped")
                        .HasColumnType("boolean");

                    b.Property<int>("InventorySlotNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Game.Core.Entities.InventoryItemMod", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemModId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemModSlotId")
                        .HasColumnType("integer");

                    b.HasKey("InventoryItemId", "ItemModId");

                    b.HasIndex("ItemModId");

                    b.HasIndex("ItemModSlotId");

                    b.ToTable("InventoryItemMods");
                });

            modelBuilder.Entity("Game.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemAttribute", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("ItemId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("ItemAttributes");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Helm"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Boot"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Weapon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Accessory"
                        });
                });

            modelBuilder.Entity("Game.Core.Entities.ItemMod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemModTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Removable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ItemModTypeId");

                    b.ToTable("ItemMods");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemModAttribute", b =>
                {
                    b.Property<int>("ItemModId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("ItemModId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("ItemModAttributes");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemModSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GuaranteedItemModId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemModSlotTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Probability")
                        .HasPrecision(9, 8)
                        .HasColumnType("numeric(9,8)");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteedItemModId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemModSlotTypeId");

                    b.ToTable("ItemModSlots");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemModType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemModTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Component"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prefix"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Suffix"
                        });
                });

            modelBuilder.Entity("Game.Core.Entities.LogPreference", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("LogSettingId")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "LogSettingId");

                    b.HasIndex("LogSettingId");

                    b.ToTable("LogPreferences");
                });

            modelBuilder.Entity("Game.Core.Entities.LogSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("LogSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultValue = false,
                            Name = "Damage"
                        },
                        new
                        {
                            Id = 2,
                            DefaultValue = false,
                            Name = "Debug"
                        },
                        new
                        {
                            Id = 3,
                            DefaultValue = true,
                            Name = "Exp"
                        },
                        new
                        {
                            Id = 4,
                            DefaultValue = true,
                            Name = "Level Up"
                        },
                        new
                        {
                            Id = 5,
                            DefaultValue = true,
                            Name = "Inventory"
                        },
                        new
                        {
                            Id = 6,
                            DefaultValue = true,
                            Name = "Enemy Defeated"
                        });
                });

            modelBuilder.Entity("Game.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uuid");

                    b.Property<int>("StatPointsGained")
                        .HasColumnType("integer");

                    b.Property<int>("StatPointsUsed")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Game.Core.Entities.PlayerAttribute", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("PlayerId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("PlayerAttributes");
                });

            modelBuilder.Entity("Game.Core.Entities.PlayerSkill", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PlayerSkills");
                });

            modelBuilder.Entity("Game.Core.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseDamage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("CooldownMs")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Game.Core.Entities.SkillDamageMultiplier", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("SkillId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("SkillDamageMultipliers");
                });

            modelBuilder.Entity("Game.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TagCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagCategoryId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Game.Core.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TagCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Accessory"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Armor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Magical"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Material"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Modification"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Usage"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Weapon"
                        });
                });

            modelBuilder.Entity("Game.Core.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LevelMax")
                        .HasColumnType("integer");

                    b.Property<int>("LevelMin")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Game.Core.Entities.ZoneDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DropRate")
                        .HasPrecision(9, 8)
                        .HasColumnType("numeric(9,8)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneDrops");
                });

            modelBuilder.Entity("Game.Core.Entities.ZoneEnemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneEnemies");
                });

            modelBuilder.Entity("ItemModTag", b =>
                {
                    b.Property<int>("ItemModsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ItemModsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ItemModTags", (string)null);
                });

            modelBuilder.Entity("ItemTag", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ItemTags", (string)null);
                });

            modelBuilder.Entity("Game.Core.Entities.AttributeDistribution", b =>
                {
                    b.HasOne("Game.Core.Entities.Attribute", "Attribute")
                        .WithMany("AttributeDistributions")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Enemy", "Enemy")
                        .WithMany("AttributeDistributions")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Game.Core.Entities.EnemyDrop", b =>
                {
                    b.HasOne("Game.Core.Entities.Enemy", "Enemy")
                        .WithMany("EnemyDrops")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Item", "Item")
                        .WithMany("EnemyDrops")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Game.Core.Entities.EnemySkill", b =>
                {
                    b.HasOne("Game.Core.Entities.Enemy", "Enemy")
                        .WithMany("EnemySkills")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Skill", "Skill")
                        .WithMany("EnemySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Game.Core.Entities.EquipmentSlot", b =>
                {
                    b.HasOne("Game.Core.Entities.ItemCategory", "ItemCategory")
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("Game.Core.Entities.InventoryItem", b =>
                {
                    b.HasOne("Game.Core.Entities.Item", "Item")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Player", "Player")
                        .WithMany("InventoryItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Core.Entities.InventoryItemMod", b =>
                {
                    b.HasOne("Game.Core.Entities.InventoryItem", "InventoryItem")
                        .WithMany("InventoryItemMods")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.ItemMod", "ItemMod")
                        .WithMany("InventoryItemMods")
                        .HasForeignKey("ItemModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.ItemModSlot", "ItemModSlot")
                        .WithMany("InventoryItemMods")
                        .HasForeignKey("ItemModSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("ItemMod");

                    b.Navigation("ItemModSlot");
                });

            modelBuilder.Entity("Game.Core.Entities.Item", b =>
                {
                    b.HasOne("Game.Core.Entities.ItemCategory", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemAttribute", b =>
                {
                    b.HasOne("Game.Core.Entities.Attribute", "Attribute")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Item", "Item")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemMod", b =>
                {
                    b.HasOne("Game.Core.Entities.ItemModType", "ItemModType")
                        .WithMany("ItemMods")
                        .HasForeignKey("ItemModTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemModType");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemModAttribute", b =>
                {
                    b.HasOne("Game.Core.Entities.Attribute", "Attribute")
                        .WithMany("ItemModAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.ItemMod", "ItemMod")
                        .WithMany("ItemModAttributes")
                        .HasForeignKey("ItemModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("ItemMod");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemModSlot", b =>
                {
                    b.HasOne("Game.Core.Entities.ItemMod", "GuaranteedItemMod")
                        .WithMany("GuaranteedSlots")
                        .HasForeignKey("GuaranteedItemModId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Game.Core.Entities.Item", "Item")
                        .WithMany("ItemModSlots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.ItemModType", "ItemModSlotType")
                        .WithMany("ItemModSlots")
                        .HasForeignKey("ItemModSlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuaranteedItemMod");

                    b.Navigation("Item");

                    b.Navigation("ItemModSlotType");
                });

            modelBuilder.Entity("Game.Core.Entities.LogPreference", b =>
                {
                    b.HasOne("Game.Core.Entities.LogSetting", "LogSetting")
                        .WithMany("LogPreferences")
                        .HasForeignKey("LogSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Player", "Player")
                        .WithMany("LogPreferences")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogSetting");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Core.Entities.PlayerAttribute", b =>
                {
                    b.HasOne("Game.Core.Entities.Attribute", "Attribute")
                        .WithMany("PlayerAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Player", "Player")
                        .WithMany("PlayerAttributes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Core.Entities.PlayerSkill", b =>
                {
                    b.HasOne("Game.Core.Entities.Player", "Player")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Skill", "Skill")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Game.Core.Entities.SkillDamageMultiplier", b =>
                {
                    b.HasOne("Game.Core.Entities.Attribute", "Attribute")
                        .WithMany("SkillDamageMultipliers")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Skill", "Skill")
                        .WithMany("SkillDamageMultipliers")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Game.Core.Entities.Tag", b =>
                {
                    b.HasOne("Game.Core.Entities.TagCategory", "TagCategory")
                        .WithMany("Tags")
                        .HasForeignKey("TagCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagCategory");
                });

            modelBuilder.Entity("Game.Core.Entities.ZoneDrop", b =>
                {
                    b.HasOne("Game.Core.Entities.Item", "Item")
                        .WithMany("ZoneDrops")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Zone", "Zone")
                        .WithMany("ZoneDrops")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Game.Core.Entities.ZoneEnemy", b =>
                {
                    b.HasOne("Game.Core.Entities.Enemy", "Enemy")
                        .WithMany("ZoneEnemies")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Zone", "Zone")
                        .WithMany("ZoneEnemies")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ItemModTag", b =>
                {
                    b.HasOne("Game.Core.Entities.ItemMod", null)
                        .WithMany()
                        .HasForeignKey("ItemModsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemTag", b =>
                {
                    b.HasOne("Game.Core.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Core.Entities.Attribute", b =>
                {
                    b.Navigation("AttributeDistributions");

                    b.Navigation("ItemAttributes");

                    b.Navigation("ItemModAttributes");

                    b.Navigation("PlayerAttributes");

                    b.Navigation("SkillDamageMultipliers");
                });

            modelBuilder.Entity("Game.Core.Entities.Enemy", b =>
                {
                    b.Navigation("AttributeDistributions");

                    b.Navigation("EnemyDrops");

                    b.Navigation("EnemySkills");

                    b.Navigation("ZoneEnemies");
                });

            modelBuilder.Entity("Game.Core.Entities.InventoryItem", b =>
                {
                    b.Navigation("InventoryItemMods");
                });

            modelBuilder.Entity("Game.Core.Entities.Item", b =>
                {
                    b.Navigation("EnemyDrops");

                    b.Navigation("InventoryItems");

                    b.Navigation("ItemAttributes");

                    b.Navigation("ItemModSlots");

                    b.Navigation("ZoneDrops");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemCategory", b =>
                {
                    b.Navigation("EquipmentSlots");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemMod", b =>
                {
                    b.Navigation("GuaranteedSlots");

                    b.Navigation("InventoryItemMods");

                    b.Navigation("ItemModAttributes");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemModSlot", b =>
                {
                    b.Navigation("InventoryItemMods");
                });

            modelBuilder.Entity("Game.Core.Entities.ItemModType", b =>
                {
                    b.Navigation("ItemModSlots");

                    b.Navigation("ItemMods");
                });

            modelBuilder.Entity("Game.Core.Entities.LogSetting", b =>
                {
                    b.Navigation("LogPreferences");
                });

            modelBuilder.Entity("Game.Core.Entities.Player", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("LogPreferences");

                    b.Navigation("PlayerAttributes");

                    b.Navigation("PlayerSkills");
                });

            modelBuilder.Entity("Game.Core.Entities.Skill", b =>
                {
                    b.Navigation("EnemySkills");

                    b.Navigation("PlayerSkills");

                    b.Navigation("SkillDamageMultipliers");
                });

            modelBuilder.Entity("Game.Core.Entities.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Game.Core.Entities.Zone", b =>
                {
                    b.Navigation("ZoneDrops");

                    b.Navigation("ZoneEnemies");
                });
#pragma warning restore 612, 618
        }
    }
}
